#pragma once

// Keep this list aligned with `tmp/llama.cpp/ggml/include/ggml.h` (`enum ggml_op`),
// excluding sentinel entries (`NONE`, `COUNT`).
#define EMEL_KERNEL_OP_EVENT_LIST(X) \
  X(op_dup) \
  X(op_add) \
  X(op_add_id) \
  X(op_add1) \
  X(op_acc) \
  X(op_sub) \
  X(op_mul) \
  X(op_div) \
  X(op_sqr) \
  X(op_sqrt) \
  X(op_log) \
  X(op_sin) \
  X(op_cos) \
  X(op_sum) \
  X(op_sum_rows) \
  X(op_cumsum) \
  X(op_mean) \
  X(op_argmax) \
  X(op_count_equal) \
  X(op_repeat) \
  X(op_repeat_back) \
  X(op_concat) \
  X(op_silu_back) \
  X(op_norm) \
  X(op_rms_norm) \
  X(op_rms_norm_back) \
  X(op_group_norm) \
  X(op_l2_norm) \
  X(op_mul_mat) \
  X(op_mul_mat_id) \
  X(op_out_prod) \
  X(op_scale) \
  X(op_set) \
  X(op_cpy) \
  X(op_cont) \
  X(op_reshape) \
  X(op_view) \
  X(op_permute) \
  X(op_transpose) \
  X(op_get_rows) \
  X(op_get_rows_back) \
  X(op_set_rows) \
  X(op_diag) \
  X(op_diag_mask_inf) \
  X(op_diag_mask_zero) \
  X(op_soft_max) \
  X(op_soft_max_back) \
  X(op_rope) \
  X(op_rope_back) \
  X(op_clamp) \
  X(op_conv_transpose_1d) \
  X(op_im2col) \
  X(op_im2col_back) \
  X(op_im2col_3d) \
  X(op_conv_2d) \
  X(op_conv_3d) \
  X(op_conv_2d_dw) \
  X(op_conv_transpose_2d) \
  X(op_pool_1d) \
  X(op_pool_2d) \
  X(op_pool_2d_back) \
  X(op_upscale) \
  X(op_pad) \
  X(op_pad_reflect_1d) \
  X(op_roll) \
  X(op_arange) \
  X(op_timestep_embedding) \
  X(op_argsort) \
  X(op_top_k) \
  X(op_leaky_relu) \
  X(op_tri) \
  X(op_fill) \
  X(op_flash_attn_ext) \
  X(op_flash_attn_back) \
  X(op_ssm_conv) \
  X(op_ssm_scan) \
  X(op_win_part) \
  X(op_win_unpart) \
  X(op_get_rel_pos) \
  X(op_add_rel_pos) \
  X(op_rwkv_wkv6) \
  X(op_gated_linear_attn) \
  X(op_rwkv_wkv7) \
  X(op_solve_tri) \
  X(op_unary) \
  X(op_map_custom1) \
  X(op_map_custom2) \
  X(op_map_custom3) \
  X(op_custom) \
  X(op_cross_entropy_loss) \
  X(op_cross_entropy_loss_back) \
  X(op_opt_step_adamw) \
  X(op_opt_step_sgd) \
  X(op_glu)
