stateDiagram-v2
  direction TB
  [*] --> state_uninitialized
  state_uninitialized --> state_bind_contract_decision : initialize_run [always] / none
  state_bind_contract_decision --> state_binding : completion_initialize_run_ [guard_bind_contract_valid_] / effect_bind_contract_
  state_bind_contract_decision --> state_init_failed_error_out_decision : completion_initialize_run_ [guard_bind_contract_invalid_] / effect_mark_bind_failed_
  state_binding --> state_lmgen_mode_decision : completion_initialize_run_ [always] / none
  state_lmgen_mode_decision --> state_configure_lmgen : completion_initialize_run_ [guard_personaplex_lmgen_] / effect_configure_personaplex_lmgen_
  state_lmgen_mode_decision --> state_configure_lmgen : completion_initialize_run_ [guard_standard_lmgen_] / effect_configure_standard_lmgen_
  state_configure_lmgen --> state_reserve_memory : completion_initialize_run_ [always] / effect_reserve_memory_
  state_reserve_memory --> state_reserve_memory_decision : completion_initialize_run_ [always] / none
  state_reserve_memory_decision --> state_allocate_sequence : completion_initialize_run_ [guard_memory_accepted_] / effect_allocate_sequence_
  state_reserve_memory_decision --> state_init_failed_error_out_decision : completion_initialize_run_ [guard_memory_rejected_] / initialize_run__
  state_allocate_sequence --> state_allocate_sequence_decision : completion_initialize_run_ [always] / none
  state_allocate_sequence_decision --> state_init_error_out_decision : completion_initialize_run_ [guard_memory_accepted_] / none
  state_allocate_sequence_decision --> state_init_failed_error_out_decision : completion_initialize_run_ [guard_memory_rejected_] / initialize_run__
  state_init_error_out_decision --> state_init_callback_decision : completion_initialize_run_ [initialize_run__] / initialize_run__
  state_init_error_out_decision --> state_init_callback_decision : completion_initialize_run_ [initialize_run__] / none
  state_init_failed_error_out_decision --> state_init_failed_callback_decision : completion_initialize_run_ [initialize_run__] / initialize_run__
  state_init_failed_error_out_decision --> state_init_failed_callback_decision : completion_initialize_run_ [initialize_run__] / none
  state_init_callback_decision --> state_session_ready : completion_initialize_run_ [initialize_run__] / effect_emit_initialize_done_
  state_init_callback_decision --> state_session_ready : completion_initialize_run_ [initialize_run__] / none
  state_init_failed_callback_decision --> state_uninitialized : completion_initialize_run_ [initialize_run__] / effect_emit_initialize_error_
  state_init_failed_callback_decision --> state_uninitialized : completion_initialize_run_ [initialize_run__] / none
  state_session_ready --> state_voice_request_decision : load_voice_run [always] / none
  state_voice_request_decision --> state_voice_error_out_decision : completion_load_voice_run_ [guard_voice_contract_valid_] / effect_bind_voice_contract_
  state_voice_request_decision --> state_voice_failed_error_out_decision : completion_load_voice_run_ [guard_voice_contract_invalid_] / load_voice_run__
  state_voice_error_out_decision --> state_voice_callback_decision : completion_load_voice_run_ [load_voice_run__] / load_voice_run__
  state_voice_error_out_decision --> state_voice_callback_decision : completion_load_voice_run_ [load_voice_run__] / none
  state_voice_failed_error_out_decision --> state_voice_failed_callback_decision : completion_load_voice_run_ [load_voice_run__] / load_voice_run__
  state_voice_failed_error_out_decision --> state_voice_failed_callback_decision : completion_load_voice_run_ [load_voice_run__] / none
  state_voice_callback_decision --> state_session_ready : completion_load_voice_run_ [load_voice_run__] / effect_emit_load_voice_done_
  state_voice_callback_decision --> state_session_ready : completion_load_voice_run_ [load_voice_run__] / none
  state_voice_failed_callback_decision --> state_session_ready : completion_load_voice_run_ [load_voice_run__] / effect_emit_load_voice_error_
  state_voice_failed_callback_decision --> state_session_ready : completion_load_voice_run_ [load_voice_run__] / none
  state_session_ready --> state_prefill_voice_request_decision : prefill_voice_run [always] / none
  state_prefill_voice_request_decision --> state_prefill_voice_allocate_slot : completion_prefill_voice_run_ [guard_voice_prefill_request_valid_] / effect_allocate_voice_prefill_slot_
  state_prefill_voice_request_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_voice_prefill_request_invalid_] / prefill_voice_run__
  state_prefill_voice_allocate_slot --> state_prefill_voice_allocate_slot_decision : completion_prefill_voice_run_ [always] / none
  state_prefill_voice_allocate_slot_decision --> state_prefill_voice_capture_memory : completion_prefill_voice_run_ [guard_memory_accepted_] / effect_capture_voice_prefill_memory_
  state_prefill_voice_allocate_slot_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_memory_rejected_] / prefill_voice_run__
  state_prefill_voice_capture_memory --> state_prefill_voice_capture_memory_decision : completion_prefill_voice_run_ [always] / none
  state_prefill_voice_capture_memory_decision --> state_prefill_voice_begin : completion_prefill_voice_run_ [guard_memory_accepted_] / effect_begin_voice_prefill_
  state_prefill_voice_capture_memory_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_memory_rejected_] / prefill_voice_run__
  state_prefill_voice_begin --> state_prefill_voice_embedding_frame : completion_prefill_voice_run_ [guard_voice_embedding_frame_f32_] / effect_load_voice_embedding_frame_f32_
  state_prefill_voice_begin --> state_prefill_voice_embedding_frame : completion_prefill_voice_run_ [guard_voice_embedding_frame_f16_] / effect_load_voice_embedding_frame_f16_
  state_prefill_voice_begin --> state_prefill_voice_embedding_frame : completion_prefill_voice_run_ [guard_voice_embedding_frame_bf16_] / effect_load_voice_embedding_frame_bf16_
  state_prefill_voice_embedding_frame --> state_prefill_voice_embedding_frame_decision : completion_prefill_voice_run_ [always] / none
  state_prefill_voice_embedding_frame_decision --> state_prefill_voice_graph_runtime_decision : completion_prefill_voice_run_ [guard_voice_embedding_frame_loaded_] / none
  state_prefill_voice_embedding_frame_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_voice_embedding_frame_failed_] / prefill_voice_run__
  state_prefill_voice_graph_runtime_decision --> state_prefill_voice_running_graph : completion_prefill_voice_run_ [guard_graph_runtime_available_] / effect_run_voice_graph_runtime_
  state_prefill_voice_graph_runtime_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_graph_runtime_unavailable_] / prefill_voice_run__
  state_prefill_voice_running_graph --> state_prefill_voice_graph_error_out_decision : completion_prefill_voice_run_ [always] / none
  state_prefill_voice_graph_error_out_decision --> state_prefill_voice_graph_result_decision : completion_prefill_voice_run_ [guard_has_graph_error_out_] / effect_store_graph_error_out_
  state_prefill_voice_graph_error_out_decision --> state_prefill_voice_graph_result_decision : completion_prefill_voice_run_ [guard_no_graph_error_out_] / none
  state_prefill_voice_graph_result_decision --> state_prefill_voice_advance : completion_prefill_voice_run_ [guard_graph_step_accepted_] / effect_advance_voice_prefill_
  state_prefill_voice_graph_result_decision --> state_prefill_voice_failed_error_out_decision : completion_prefill_voice_run_ [guard_graph_step_rejected_] / prefill_voice_run__
  state_prefill_voice_advance --> state_prefill_voice_complete_decision : completion_prefill_voice_run_ [always] / none
  state_prefill_voice_complete_decision --> state_prefill_voice_output_decision : completion_prefill_voice_run_ [guard_voice_prefill_complete_] / effect_copy_voice_cache_
  state_prefill_voice_complete_decision --> state_prefill_voice_output_decision : completion_prefill_voice_run_ [guard_voice_prefill_pending_] / none
  state_prefill_voice_output_decision --> state_prefill_voice_remaining_out_decision : completion_prefill_voice_run_ [guard_has_voice_complete_out_] / effect_store_voice_complete_out_
  state_prefill_voice_output_decision --> state_prefill_voice_remaining_out_decision : completion_prefill_voice_run_ [guard_no_voice_complete_out_] / none
  state_prefill_voice_remaining_out_decision --> state_prefill_voice_error_out_decision : completion_prefill_voice_run_ [guard_has_voice_remaining_out_] / effect_store_voice_remaining_out_
  state_prefill_voice_remaining_out_decision --> state_prefill_voice_error_out_decision : completion_prefill_voice_run_ [guard_no_voice_remaining_out_] / none
  state_prefill_voice_error_out_decision --> state_prefill_voice_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / prefill_voice_run__
  state_prefill_voice_error_out_decision --> state_prefill_voice_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_prefill_voice_failed_error_out_decision --> state_prefill_voice_failed_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / prefill_voice_run__
  state_prefill_voice_failed_error_out_decision --> state_prefill_voice_failed_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_prefill_voice_callback_decision --> state_session_ready : completion_prefill_voice_run_ [prefill_voice_run__] / effect_emit_prefill_voice_done_
  state_prefill_voice_callback_decision --> state_session_ready : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_prefill_voice_failed_callback_decision --> state_session_ready : completion_prefill_voice_run_ [prefill_voice_run__] / effect_emit_prefill_voice_error_
  state_prefill_voice_failed_callback_decision --> state_session_ready : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_session_ready --> state_personaplex_prompt_begin_decision : begin_personaplex_prompt_run [always] / none
  state_personaplex_prompt_begin_decision --> state_personaplex_prompt_begin_error_out_decision : completion_begin_personaplex_prompt_run_ [guard_personaplex_prompt_begin_nonempty_valid_] / effect_bind_personaplex_prompt_
  state_personaplex_prompt_begin_decision --> state_personaplex_prompt_begin_error_out_decision : completion_begin_personaplex_prompt_run_ [guard_personaplex_prompt_begin_empty_valid_] / effect_bind_empty_personaplex_prompt_
  state_personaplex_prompt_begin_decision --> state_personaplex_prompt_begin_failed_error_out_decision : completion_begin_personaplex_prompt_run_ [guard_personaplex_prompt_begin_invalid_] / begin_personaplex_prompt_run__
  state_personaplex_prompt_begin_error_out_decision --> state_personaplex_prompt_begin_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / begin_personaplex_prompt_run__
  state_personaplex_prompt_begin_error_out_decision --> state_personaplex_prompt_begin_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_personaplex_prompt_begin_failed_error_out_decision --> state_personaplex_prompt_begin_failed_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / begin_personaplex_prompt_run__
  state_personaplex_prompt_begin_failed_error_out_decision --> state_personaplex_prompt_begin_failed_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_personaplex_prompt_begin_callback_decision --> state_session_ready : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / effect_emit_begin_personaplex_prompt_done_
  state_personaplex_prompt_begin_callback_decision --> state_session_ready : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_personaplex_prompt_begin_failed_callback_decision --> state_session_ready : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / effect_emit_begin_personaplex_prompt_error_
  state_personaplex_prompt_begin_failed_callback_decision --> state_session_ready : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_session_ready --> state_prefill_personaplex_prompt_request_decision : prefill_personaplex_prompt_run [always] / none
  state_prefill_personaplex_prompt_request_decision --> state_prefill_personaplex_prompt_allocate_slot : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_prefill_request_valid_] / effect_allocate_personaplex_prompt_slot_
  state_prefill_personaplex_prompt_request_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_prefill_request_invalid_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_allocate_slot --> state_prefill_personaplex_prompt_allocate_slot_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_allocate_slot_decision --> state_prefill_personaplex_prompt_capture_memory : completion_prefill_personaplex_prompt_run_ [guard_memory_accepted_] / effect_capture_personaplex_prompt_memory_
  state_prefill_personaplex_prompt_allocate_slot_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_memory_rejected_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_capture_memory --> state_prefill_personaplex_prompt_capture_memory_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_capture_memory_decision --> state_prefill_personaplex_prompt_begin : completion_prefill_personaplex_prompt_run_ [guard_memory_accepted_] / effect_begin_personaplex_prompt_prefill_
  state_prefill_personaplex_prompt_capture_memory_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_memory_rejected_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_begin --> state_prefill_personaplex_prompt_phase_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_phase_decision --> state_prefill_personaplex_prompt_frame : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_pre_silence_pending_] / effect_build_personaplex_prompt_silence_frame_
  state_prefill_personaplex_prompt_phase_decision --> state_prefill_personaplex_prompt_frame : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_text_pending_] / effect_build_personaplex_prompt_text_frame_
  state_prefill_personaplex_prompt_phase_decision --> state_prefill_personaplex_prompt_frame : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_post_silence_pending_] / effect_build_personaplex_prompt_silence_frame_
  state_prefill_personaplex_prompt_phase_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_phase_invalid_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_frame --> state_prefill_personaplex_prompt_write_input : completion_prefill_personaplex_prompt_run_ [always] / effect_write_and_build_personaplex_prompt_input_
  state_prefill_personaplex_prompt_write_input --> state_prefill_personaplex_prompt_graph_runtime_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_graph_runtime_decision --> state_prefill_personaplex_prompt_running_graph : completion_prefill_personaplex_prompt_run_ [guard_graph_runtime_available_] / effect_run_personaplex_prompt_graph_runtime_
  state_prefill_personaplex_prompt_graph_runtime_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_graph_runtime_unavailable_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_running_graph --> state_prefill_personaplex_prompt_graph_error_out_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_graph_error_out_decision --> state_prefill_personaplex_prompt_graph_result_decision : completion_prefill_personaplex_prompt_run_ [guard_has_graph_error_out_] / effect_store_graph_error_out_
  state_prefill_personaplex_prompt_graph_error_out_decision --> state_prefill_personaplex_prompt_graph_result_decision : completion_prefill_personaplex_prompt_run_ [guard_no_graph_error_out_] / none
  state_prefill_personaplex_prompt_graph_result_decision --> state_prefill_personaplex_prompt_advance : completion_prefill_personaplex_prompt_run_ [guard_graph_step_accepted_personaplex_prompt_pre_silence_] / effect_advance_personaplex_prompt_pre_silence_
  state_prefill_personaplex_prompt_graph_result_decision --> state_prefill_personaplex_prompt_advance : completion_prefill_personaplex_prompt_run_ [guard_graph_step_accepted_personaplex_prompt_text_] / effect_advance_personaplex_prompt_text_
  state_prefill_personaplex_prompt_graph_result_decision --> state_prefill_personaplex_prompt_advance : completion_prefill_personaplex_prompt_run_ [guard_graph_step_accepted_personaplex_prompt_post_silence_] / effect_advance_personaplex_prompt_post_silence_
  state_prefill_personaplex_prompt_graph_result_decision --> state_prefill_personaplex_prompt_failed_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_graph_step_rejected_] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_advance --> state_prefill_personaplex_prompt_complete_decision : completion_prefill_personaplex_prompt_run_ [always] / none
  state_prefill_personaplex_prompt_complete_decision --> state_prefill_personaplex_prompt_output_decision : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_complete_] / effect_finish_personaplex_prompt_
  state_prefill_personaplex_prompt_complete_decision --> state_prefill_personaplex_prompt_output_decision : completion_prefill_personaplex_prompt_run_ [guard_personaplex_prompt_pending_] / effect_publish_personaplex_prompt_pending_
  state_prefill_personaplex_prompt_output_decision --> state_prefill_personaplex_prompt_remaining_out_decision : completion_prefill_personaplex_prompt_run_ [guard_has_personaplex_prompt_complete_out_] / effect_store_personaplex_prompt_complete_out_
  state_prefill_personaplex_prompt_output_decision --> state_prefill_personaplex_prompt_remaining_out_decision : completion_prefill_personaplex_prompt_run_ [guard_no_personaplex_prompt_complete_out_] / none
  state_prefill_personaplex_prompt_remaining_out_decision --> state_prefill_personaplex_prompt_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_has_personaplex_prompt_remaining_out_] / effect_store_personaplex_prompt_remaining_out_
  state_prefill_personaplex_prompt_remaining_out_decision --> state_prefill_personaplex_prompt_error_out_decision : completion_prefill_personaplex_prompt_run_ [guard_no_personaplex_prompt_remaining_out_] / none
  state_prefill_personaplex_prompt_error_out_decision --> state_prefill_personaplex_prompt_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_error_out_decision --> state_prefill_personaplex_prompt_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_prefill_personaplex_prompt_failed_error_out_decision --> state_prefill_personaplex_prompt_failed_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / prefill_personaplex_prompt_run__
  state_prefill_personaplex_prompt_failed_error_out_decision --> state_prefill_personaplex_prompt_failed_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_prefill_personaplex_prompt_callback_decision --> state_session_ready : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / effect_emit_prefill_personaplex_prompt_done_
  state_prefill_personaplex_prompt_callback_decision --> state_session_ready : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_prefill_personaplex_prompt_failed_callback_decision --> state_session_ready : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / effect_emit_prefill_personaplex_prompt_error_
  state_prefill_personaplex_prompt_failed_callback_decision --> state_session_ready : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_session_ready --> state_step_request_decision : step_run [always] / none
  state_step_request_decision --> state_allocate_step_slot : completion_step_run_ [guard_step_request_valid_] / effect_allocate_step_slot_
  state_step_request_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_step_blocked_by_voice_prompt_] / effect_mark_voice_prompt_pending_
  state_step_request_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_step_request_shape_invalid_] / effect_mark_step_request_invalid_
  state_allocate_step_slot --> state_allocate_step_slot_decision : completion_step_run_ [always] / none
  state_allocate_step_slot_decision --> state_capture_memory : completion_step_run_ [guard_memory_accepted_] / effect_capture_memory_
  state_allocate_step_slot_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_memory_rejected_] / step_run__
  state_capture_memory --> state_capture_memory_decision : completion_step_run_ [always] / none
  state_capture_memory_decision --> state_step_begin : completion_step_run_ [guard_memory_accepted_] / effect_begin_step_
  state_capture_memory_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_memory_rejected_] / step_run__
  state_step_begin --> state_input_write_decision : completion_step_run_ [always] / none
  state_input_write_decision --> state_build_input_sequence : completion_step_run_ [guard_has_full_input_] / effect_write_full_input_
  state_input_write_decision --> state_build_input_sequence : completion_step_run_ [guard_has_tail_input_] / effect_write_tail_input_
  state_input_write_decision --> state_build_input_sequence : completion_step_run_ [guard_has_no_input_write_] / none
  state_build_input_sequence --> state_graph_runtime_decision : completion_step_run_ [always] / effect_build_input_sequence_
  state_graph_runtime_decision --> state_running_graph : completion_step_run_ [guard_graph_runtime_available_] / effect_run_graph_runtime_
  state_graph_runtime_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_graph_runtime_unavailable_] / step_run__
  state_running_graph --> state_graph_error_out_decision : completion_step_run_ [always] / none
  state_graph_error_out_decision --> state_graph_result_decision : completion_step_run_ [guard_has_graph_error_out_] / effect_store_graph_error_out_
  state_graph_error_out_decision --> state_graph_result_decision : completion_step_run_ [guard_no_graph_error_out_] / none
  state_graph_result_decision --> state_depformer_decision : completion_step_run_ [guard_graph_step_accepted_] / none
  state_graph_result_decision --> state_step_failed_error_out_decision : completion_step_run_ [guard_graph_step_rejected_] / step_run__
  state_depformer_decision --> state_apply_delay_mask : completion_step_run_ [guard_replace_depformer_tokens_] / effect_replace_audio_with_zero_
  state_depformer_decision --> state_apply_delay_mask : completion_step_run_ [guard_use_graph_audio_tokens_] / none
  state_apply_delay_mask --> state_write_generated_decision : completion_step_run_ [always] / effect_apply_delay_mask_and_advance_
  state_write_generated_decision --> state_skip_delay_decision : completion_step_run_ [guard_should_write_generated_] / effect_write_generated_
  state_write_generated_decision --> state_skip_delay_decision : completion_step_run_ [guard_provided_input_] / effect_write_generated_missing_
  state_skip_delay_decision --> state_step_produced_out_decision : completion_step_run_ [guard_skip_pending_] / effect_consume_skip_
  state_skip_delay_decision --> state_step_produced_out_decision : completion_step_run_ [guard_before_delay_] / effect_publish_no_output_
  state_skip_delay_decision --> state_collect_output : completion_step_run_ [guard_past_delay_] / effect_collect_delayed_output_
  state_collect_output --> state_output_decision : completion_step_run_ [always] / none
  state_output_decision --> state_step_produced_out_decision : completion_step_run_ [guard_output_has_ungenerated_] / effect_publish_no_output_
  state_output_decision --> state_step_produced_out_decision : completion_step_run_ [guard_output_complete_] / effect_publish_output_
  state_step_produced_out_decision --> state_step_error_out_decision : completion_step_run_ [guard_has_produced_out_] / effect_store_produced_out_
  state_step_produced_out_decision --> state_step_error_out_decision : completion_step_run_ [guard_no_produced_out_] / none
  state_step_error_out_decision --> state_step_callback_decision : completion_step_run_ [step_run__] / step_run__
  state_step_error_out_decision --> state_step_callback_decision : completion_step_run_ [step_run__] / none
  state_step_failed_error_out_decision --> state_step_failed_callback_decision : completion_step_run_ [step_run__] / step_run__
  state_step_failed_error_out_decision --> state_step_failed_callback_decision : completion_step_run_ [step_run__] / none
  state_step_callback_decision --> state_session_ready : completion_step_run_ [step_run__] / effect_emit_step_done_
  state_step_callback_decision --> state_session_ready : completion_step_run_ [step_run__] / none
  state_step_failed_callback_decision --> state_session_ready : completion_step_run_ [step_run__] / effect_emit_step_error_
  state_step_failed_callback_decision --> state_session_ready : completion_step_run_ [step_run__] / none
  state_uninitialized --> state_uninit_step_error_out_decision : step_run [always] / step_run__
  state_uninit_step_error_out_decision --> state_uninit_step_callback_decision : completion_step_run_ [step_run__] / step_run__
  state_uninit_step_error_out_decision --> state_uninit_step_callback_decision : completion_step_run_ [step_run__] / none
  state_uninit_step_callback_decision --> state_uninitialized : completion_step_run_ [step_run__] / effect_emit_step_error_
  state_uninit_step_callback_decision --> state_uninitialized : completion_step_run_ [step_run__] / none
  state_uninitialized --> state_uninit_voice_error_out_decision : load_voice_run [always] / load_voice_run__
  state_uninit_voice_error_out_decision --> state_uninit_voice_callback_decision : completion_load_voice_run_ [load_voice_run__] / load_voice_run__
  state_uninit_voice_error_out_decision --> state_uninit_voice_callback_decision : completion_load_voice_run_ [load_voice_run__] / none
  state_uninit_voice_callback_decision --> state_uninitialized : completion_load_voice_run_ [load_voice_run__] / effect_emit_load_voice_error_
  state_uninit_voice_callback_decision --> state_uninitialized : completion_load_voice_run_ [load_voice_run__] / none
  state_uninitialized --> state_uninit_prefill_voice_error_out_decision : prefill_voice_run [always] / prefill_voice_run__
  state_uninit_prefill_voice_error_out_decision --> state_uninit_prefill_voice_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / prefill_voice_run__
  state_uninit_prefill_voice_error_out_decision --> state_uninit_prefill_voice_callback_decision : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_uninit_prefill_voice_callback_decision --> state_uninitialized : completion_prefill_voice_run_ [prefill_voice_run__] / effect_emit_prefill_voice_error_
  state_uninit_prefill_voice_callback_decision --> state_uninitialized : completion_prefill_voice_run_ [prefill_voice_run__] / none
  state_uninitialized --> state_uninit_begin_personaplex_prompt_error_out_decision : begin_personaplex_prompt_run [always] / begin_personaplex_prompt_run__
  state_uninit_begin_personaplex_prompt_error_out_decision --> state_uninit_begin_personaplex_prompt_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / begin_personaplex_prompt_run__
  state_uninit_begin_personaplex_prompt_error_out_decision --> state_uninit_begin_personaplex_prompt_callback_decision : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_uninit_begin_personaplex_prompt_callback_decision --> state_uninitialized : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / effect_emit_begin_personaplex_prompt_error_
  state_uninit_begin_personaplex_prompt_callback_decision --> state_uninitialized : completion_begin_personaplex_prompt_run_ [begin_personaplex_prompt_run__] / none
  state_uninitialized --> state_uninit_prefill_personaplex_prompt_error_out_decision : prefill_personaplex_prompt_run [always] / prefill_personaplex_prompt_run__
  state_uninit_prefill_personaplex_prompt_error_out_decision --> state_uninit_prefill_personaplex_prompt_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / prefill_personaplex_prompt_run__
  state_uninit_prefill_personaplex_prompt_error_out_decision --> state_uninit_prefill_personaplex_prompt_callback_decision : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_uninit_prefill_personaplex_prompt_callback_decision --> state_uninitialized : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / effect_emit_prefill_personaplex_prompt_error_
  state_uninit_prefill_personaplex_prompt_callback_decision --> state_uninitialized : completion_prefill_personaplex_prompt_run_ [prefill_personaplex_prompt_run__] / none
  state_session_ready --> state_uninitialized : reset_run [always] / effect_reset_session_
  state_uninitialized --> state_uninitialized : _ [guard_unexpected_error_out_present_] / effect_mark_unexpected_and_store_
  state_uninitialized --> state_uninitialized : _ [guard_unexpected_error_out_absent_] / effect_mark_unexpected_
