stateDiagram-v2
  direction TB
  [*] --> state_ready
  state_ready --> state_runtime_decision : encode_run [always] / none
  state_runtime_decision --> state_shape_decision : completion_encode_run_ [guard_runtime_bound_] / none
  state_runtime_decision --> state_error_error_out_decision : completion_encode_run_ [guard_runtime_unbound_] / effect_mark_runtime_unbound_
  state_shape_decision --> state_capacity_decision : completion_encode_run_ [guard_request_shape_valid_] / none
  state_shape_decision --> state_error_error_out_decision : completion_encode_run_ [guard_request_shape_invalid_] / effect_mark_request_shape_invalid_
  state_capacity_decision --> state_frontend_variant_decision : completion_encode_run_ [guard_buffer_capacity_valid_] / none
  state_frontend_variant_decision --> state_frontend_running : completion_encode_run_ [guard_conv_f32_] / effect_run_frontend_false__
  state_frontend_variant_decision --> state_frontend_running : completion_encode_run_ [guard_conv_f16_] / effect_run_frontend_true__
  state_capacity_decision --> state_error_error_out_decision : completion_encode_run_ [guard_buffer_capacity_invalid_] / effect_mark_buffer_capacity_invalid_
  state_frontend_running --> state_transformer_variant_decision : completion_encode_run_ [always] / none
  state_transformer_variant_decision --> state_transformer_running : completion_encode_run_ [guard_proj_f32_] / effect_run_transformer_false__
  state_transformer_variant_decision --> state_transformer_running : completion_encode_run_ [guard_proj_q8_] / effect_run_transformer_true__
  state_transformer_running --> state_downsample_variant_decision : completion_encode_run_ [always] / none
  state_downsample_variant_decision --> state_downsample_running : completion_encode_run_ [guard_conv_f32_] / effect_run_downsample_false__
  state_downsample_variant_decision --> state_downsample_running : completion_encode_run_ [guard_conv_f16_] / effect_run_downsample_true__
  state_downsample_running --> state_success_error_out_decision : completion_encode_run_ [always] / none
  state_success_error_out_decision --> state_success_callback_decision : completion_encode_run_ [guard_has_error_out_] / effect_store_error_out_
  state_success_error_out_decision --> state_success_callback_decision : completion_encode_run_ [guard_no_error_out_] / none
  state_error_error_out_decision --> state_error_callback_decision : completion_encode_run_ [guard_has_error_out_] / effect_store_error_out_
  state_error_error_out_decision --> state_error_callback_decision : completion_encode_run_ [guard_no_error_out_] / none
  state_success_callback_decision --> state_done : completion_encode_run_ [guard_has_done_callback_] / effect_emit_done_
  state_success_callback_decision --> state_done : completion_encode_run_ [guard_no_done_callback_] / none
  state_error_callback_decision --> state_errored : completion_encode_run_ [guard_has_error_callback_] / effect_emit_error_
  state_error_callback_decision --> state_errored : completion_encode_run_ [guard_no_error_callback_] / none
  state_done --> state_ready : completion_encode_run_ [always] / none
  state_errored --> state_ready : completion_encode_run_ [always] / none
  state_ready --> state_ready : _ [always] / effect_on_unexpected_
  state_runtime_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_shape_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_capacity_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_frontend_variant_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_frontend_running --> state_ready : _ [always] / effect_on_unexpected_
  state_downsample_variant_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_transformer_variant_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_transformer_running --> state_ready : _ [always] / effect_on_unexpected_
  state_downsample_running --> state_ready : _ [always] / effect_on_unexpected_
  state_success_error_out_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_success_callback_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_error_error_out_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_error_callback_decision --> state_ready : _ [always] / effect_on_unexpected_
  state_done --> state_ready : _ [always] / effect_on_unexpected_
  state_errored --> state_ready : _ [always] / effect_on_unexpected_
