#ifndef EMEL_EMEL_H
#define EMEL_EMEL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum emel_status {
  EMEL_OK = 0,
  EMEL_ERR_INVALID_ARGUMENT = 1,
  EMEL_ERR_FORMAT_UNSUPPORTED = 2,
  EMEL_ERR_PARSE_FAILED = 3,
  EMEL_ERR_IO = 4,
  EMEL_ERR_MODEL_INVALID = 5,
  EMEL_ERR_BACKEND = 6,
  EMEL_ERR_INTERNAL = 7,
  EMEL_ERR_CAPACITY = 8,
  EMEL_ERR_OOM = 9,
  EMEL_ERR_UNSUPPORTED = 10,
  EMEL_ERR_UNSUPPORTED_OP = 11,
  EMEL_ERR_EMPTY = 12,
  EMEL_ERR_STOPPED = 13,
  EMEL_ERR_TEMPLATE_SYNTAX = 14,
  EMEL_ERR_TEMPLATE_RUNTIME = 15,
  EMEL_ERR_TEMPLATE_LIMIT = 16,
  EMEL_ERR_TEMPLATE_UNSUPPORTED = 17
} emel_status;

#ifdef __cplusplus
}
#endif

#endif  // EMEL_EMEL_H
