#ifndef EMEL_EMEL_H
#define EMEL_EMEL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif


// DO NOT USE THESE ARE DEPRECATED HERE ONLY FOR BACKWARD COMPATIBILITY
#define EMEL_OK 0
#define EMEL_ERR_INVALID_ARGUMENT 1
#define EMEL_ERR_FORMAT_UNSUPPORTED 2
#define EMEL_ERR_PARSE_FAILED 3
#define EMEL_ERR_IO 4
#define EMEL_ERR_MODEL_INVALID 5
#define EMEL_ERR_BACKEND 6
#define EMEL_ERR_INTERNAL 7
#define EMEL_ERR_CAPACITY 8
#define EMEL_ERR_OOM 9
#define EMEL_ERR_UNSUPPORTED 10
#define EMEL_ERR_UNSUPPORTED_OP 11
#define EMEL_ERR_EMPTY 12
#define EMEL_ERR_STOPPED 13
#define EMEL_ERR_TEMPLATE_SYNTAX 14
#define EMEL_ERR_TEMPLATE_RUNTIME 15
#define EMEL_ERR_TEMPLATE_LIMIT 16
#define EMEL_ERR_TEMPLATE_UNSUPPORTED 17

#ifdef __cplusplus
}
#endif

#endif  // EMEL_EMEL_H
