stateDiagram-v2
  [*] --> emel__batch__sanitizer__initialized
  emel__batch__sanitizer__initialized --> emel__batch__sanitizer__sanitizing : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__valid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__begin_sanitize_
  emel__batch__sanitizer__initialized --> emel__batch__sanitizer__errored : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__invalid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__reject_invalid_sanitize_
  emel__batch__sanitizer__sanitizing --> emel__batch__sanitizer__sanitize_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__run_sanitize_decode_
  emel__batch__sanitizer__sanitize_decision --> emel__batch__sanitizer__errored : [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__phase_failed_] / boost__sml__front__none
  emel__batch__sanitizer__sanitize_decision --> emel__batch__sanitizer__done : [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__mark_done_
  emel__batch__sanitizer__done --> emel__batch__sanitizer__sanitizing : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__valid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__begin_sanitize_
  emel__batch__sanitizer__done --> emel__batch__sanitizer__errored : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__invalid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__reject_invalid_sanitize_
  emel__batch__sanitizer__errored --> emel__batch__sanitizer__sanitizing : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__valid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__begin_sanitize_
  emel__batch__sanitizer__errored --> emel__batch__sanitizer__errored : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__invalid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__reject_invalid_sanitize_
  emel__batch__sanitizer__unexpected --> emel__batch__sanitizer__sanitizing : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__valid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__begin_sanitize_
  emel__batch__sanitizer__unexpected --> emel__batch__sanitizer__errored : emel__batch__sanitizer__event__sanitize_decode [boost__sml__aux__zero_wrapper_emel__batch__sanitizer__guard__invalid_request_] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__reject_invalid_sanitize_
  emel__batch__sanitizer__initialized --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
  emel__batch__sanitizer__sanitizing --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
  emel__batch__sanitizer__sanitize_decision --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
  emel__batch__sanitizer__done --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
  emel__batch__sanitizer__errored --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
  emel__batch__sanitizer__unexpected --> emel__batch__sanitizer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__sanitizer__action__on_unexpected_
