stateDiagram-v2
  [*] --> emel__batch__splitter__initialized
  emel__batch__splitter__initialized --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_9_45__] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_11_37__
  emel__batch__splitter__initialized --> emel__batch__splitter__invalid_request : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_14_5__] / boost__sml__front__none
  emel__batch__splitter__validating --> emel__batch__splitter__normalizing_batch : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_17_42__] / boost__sml__front__none
  emel__batch__splitter__validating --> emel__batch__splitter__invalid_request : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_80_5__] / boost__sml__front__none
  emel__batch__splitter__normalizing_batch --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_36_41__
  emel__batch__splitter__normalizing_batch --> emel__batch__splitter__selecting_mode : [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__selecting_mode --> emel__batch__splitter__splitting_simple : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_82_40__] / boost__sml__front__none
  emel__batch__splitter__selecting_mode --> emel__batch__splitter__splitting_equal : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_86_39__] / boost__sml__front__none
  emel__batch__splitter__selecting_mode --> emel__batch__splitter__splitting_seq : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_90_37__] / boost__sml__front__none
  emel__batch__splitter__selecting_mode --> emel__batch__splitter__invalid_request : [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting_simple --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_187_38__
  emel__batch__splitter__splitting_simple --> emel__batch__splitter__publishing : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_95_41__] / boost__sml__front__none
  emel__batch__splitter__splitting_simple --> emel__batch__splitter__split_failed : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_109_5__] / boost__sml__front__none
  emel__batch__splitter__splitting_equal --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_214_37__
  emel__batch__splitter__splitting_equal --> emel__batch__splitter__publishing : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_95_41__] / boost__sml__front__none
  emel__batch__splitter__splitting_equal --> emel__batch__splitter__split_failed : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_109_5__] / boost__sml__front__none
  emel__batch__splitter__splitting_seq --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_333_35__
  emel__batch__splitter__splitting_seq --> emel__batch__splitter__publishing : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_95_41__] / boost__sml__front__none
  emel__batch__splitter__splitting_seq --> emel__batch__splitter__split_failed : [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_109_5__] / boost__sml__front__none
  emel__batch__splitter__publishing --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_399_33__
  emel__batch__splitter__publishing --> emel__batch__splitter__done : [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__done --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_9_45__] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_11_37__
  emel__batch__splitter__done --> emel__batch__splitter__invalid_request : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_14_5__] / boost__sml__front__none
  emel__batch__splitter__invalid_request --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_9_45__] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_11_37__
  emel__batch__splitter__invalid_request --> emel__batch__splitter__invalid_request : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_14_5__] / boost__sml__front__none
  emel__batch__splitter__split_failed --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_9_45__] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_11_37__
  emel__batch__splitter__split_failed --> emel__batch__splitter__invalid_request : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_14_5__] / boost__sml__front__none
  emel__batch__splitter__unexpected_event --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_9_45__] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_11_37__
  emel__batch__splitter__unexpected_event --> emel__batch__splitter__invalid_request : emel__batch__splitter__event__split [boost__sml__aux__zero_wrapper_emel__batch__splitter__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_guards_hpp_14_5__] / boost__sml__front__none
  emel__batch__splitter__initialized --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__validating --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__normalizing_batch --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__selecting_mode --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting_simple --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting_equal --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting_seq --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__publishing --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__done --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__invalid_request --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__split_failed --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__unexpected_event --> emel__batch__splitter__unexpected_event : internal_event [boost__sml__front__always] / boost__sml__front__none
