stateDiagram-v2
  direction TB
  [*] --> preparing
  preparing --> planning : completion_request_runtime_ [always] / lambda_actions_287_39
  planning --> planning_mode_decision : completion_request_runtime_ [always] / none
  planning_mode_decision --> planning_fast_input_decision : completion_request_runtime_ [lambda_guards_13_5] / none
  planning_mode_decision --> planning_general_input_decision : completion_request_runtime_ [lambda_guards_19_5] / none
  planning_general_input_decision --> planning_general_capacity_decision : completion_request_runtime_ [lambda_guards_129_5] / none
  planning_general_input_decision --> planning_failed : completion_request_runtime_ [lambda_guards_31_5] / lambda_actions_262_48
  planning_general_capacity_decision --> planning_failed : completion_request_runtime_ [lambda_guards_70_5] / lambda_actions_277_48
  planning_general_capacity_decision --> planning_failed : completion_request_runtime_ [lambda_guards_82_5] / lambda_actions_282_50
  planning_general_capacity_decision --> planning_general_execute : completion_request_runtime_ [lambda_guards_135_5] / none
  planning_general_execute --> planning_general_result_decision : completion_request_runtime_ [always] / lambda_actions_257_45
  planning_fast_input_decision --> planning_failed : completion_request_runtime_ [lambda_guards_31_5] / lambda_actions_262_48
  planning_fast_input_decision --> planning_failed : completion_request_runtime_ [lambda_guards_43_5] / lambda_actions_267_50
  planning_fast_input_decision --> planning_failed : completion_request_runtime_ [lambda_guards_115_5] / lambda_actions_267_50
  planning_fast_input_decision --> planning_fast_capacity_decision : completion_request_runtime_ [lambda_guards_121_5] / none
  planning_fast_capacity_decision --> planning_failed : completion_request_runtime_ [lambda_guards_70_5] / lambda_actions_277_48
  planning_fast_capacity_decision --> planning_failed : completion_request_runtime_ [lambda_guards_82_5] / lambda_actions_282_50
  planning_fast_capacity_decision --> planning_fast_execute : completion_request_runtime_ [lambda_guards_135_5] / none
  planning_fast_execute --> planning_fast_result_decision : completion_request_runtime_ [always] / lambda_actions_252_55
  planning_general_result_decision --> planning_done : completion_request_runtime_ [lambda_guards_140_44] / none
  planning_general_result_decision --> planning_failed : completion_request_runtime_ [lambda_guards_145_41] / lambda_actions_272_56
  planning_fast_result_decision --> planning_done : completion_request_runtime_ [lambda_guards_140_44] / none
  planning_fast_result_decision --> planning_failed : completion_request_runtime_ [lambda_guards_145_41] / lambda_actions_272_56
  planning_done --> terminate : [always] / none
  planning_failed --> terminate : [always] / none
  preparing --> planning_failed : _ [always] / none
  planning --> planning_failed : _ [always] / none
  planning_mode_decision --> planning_failed : _ [always] / none
  planning_fast_input_decision --> planning_failed : _ [always] / none
  planning_fast_capacity_decision --> planning_failed : _ [always] / none
  planning_fast_execute --> planning_failed : _ [always] / none
  planning_general_input_decision --> planning_failed : _ [always] / none
  planning_general_capacity_decision --> planning_failed : _ [always] / none
  planning_general_execute --> planning_failed : _ [always] / none
  planning_general_result_decision --> planning_failed : _ [always] / none
  planning_fast_result_decision --> planning_failed : _ [always] / none
  planning_done --> planning_failed : _ [always] / none
  planning_failed --> planning_failed : _ [always] / none
