stateDiagram-v2
  direction TB
  [*] --> preparing
  preparing --> planning : completion [always] / lambda_actions_275_39
  planning --> planning_mode_decision : completion [always] / none
  planning_mode_decision --> planning_fast_path : completion [lambda_guards_9_5] / none
  planning_mode_decision --> planning_general : completion [always] / none
  planning_fast_path --> planning_decision : completion [always] / lambda_actions_267_5
  planning_general --> planning_decision : completion [always] / lambda_actions_271_45
  planning_decision --> planning_done : completion [lambda_guards_14_44] / none
  planning_decision --> planning_failed : completion [lambda_guards_19_41] / none
  planning_done --> terminate : [always] / none
  planning_failed --> terminate : [always] / none
  preparing --> unexpected_event : _ [always] / none
  planning --> unexpected_event : _ [always] / none
  planning_mode_decision --> unexpected_event : _ [always] / none
  planning_fast_path --> unexpected_event : _ [always] / none
  planning_general --> unexpected_event : _ [always] / none
  planning_decision --> unexpected_event : _ [always] / none
  planning_done --> unexpected_event : _ [always] / none
  planning_failed --> unexpected_event : _ [always] / none
  unexpected_event --> unexpected_event : _ [always] / none
