stateDiagram-v2
  direction TB
  [*] --> state_preparing
  state_preparing --> state_planning : plan_request [always] / lambda_actions_95_47
  state_planning --> state_planning_input_decision : completion_plan_request_ [always] / none
  state_planning_input_decision --> state_planning_failed : completion_plan_request_ [lambda_guards_26_5] / lambda_actions_101_5
  state_planning_input_decision --> state_planning_capacity_decision : completion_plan_request_ [lambda_guards_20_5] / none
  state_planning_capacity_decision --> state_planning_failed : completion_plan_request_ [lambda_guards_32_5] / lambda_actions_107_5
  state_planning_capacity_decision --> state_planning_failed : completion_plan_request_ [lambda_guards_38_5] / lambda_actions_113_5
  state_planning_capacity_decision --> state_planning_execute : completion_plan_request_ [lambda_guards_44_5] / none
  state_planning_execute --> state_planning_result_decision : completion_plan_request_ [always] / lambda_actions_31_5
  state_planning_result_decision --> state_planning_done : completion_plan_request_ [lambda_guards_52_5] / lambda_actions_12_47
  state_planning_result_decision --> state_planning_failed : completion_plan_request_ [lambda_guards_57_47] / lambda_actions_119_5
  state_planning_done --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning_failed --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_preparing --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning_input_decision --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning_capacity_decision --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning_execute --> state_planning_failed : _ [always] / lambda_actions_23_57
  state_planning_result_decision --> state_planning_failed : _ [always] / lambda_actions_23_57
