stateDiagram-v2
  direction TB
  [*] --> preparing
  preparing --> planning : completion [always] / lambda_actions_40_39
  planning --> planning_decision : completion [always] / lambda_actions_44_37
  planning_decision --> planning_done : completion [lambda_guards_7_44] / none
  planning_decision --> planning_failed : completion [lambda_guards_13_5] / none
  planning_done --> terminate : [always] / none
  planning_failed --> terminate : [always] / none
  planning_done --> planning_failed : _ [always] / none
  planning_failed --> planning_failed : _ [always] / none
  preparing --> planning_failed : _ [always] / none
  planning --> planning_failed : _ [always] / none
  planning_decision --> planning_failed : _ [always] / none
