stateDiagram-v2
  [*] --> emel::batch::splitter::initialized
  emel__batch__splitter__initialized --> emel__batch__splitter__validating : emel__batch__splitter__event__split [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_29_37__
  emel__batch__splitter__validating --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_45_11__
  emel__batch__splitter__validating --> emel__batch__splitter__validating : emel__batch__splitter__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_52_38__
  emel__batch__splitter__validating --> emel__batch__splitter__normalizing_batch : emel__batch__splitter__events__validate_done [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__validating --> emel__batch__splitter__errored : emel__batch__splitter__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__normalizing_batch --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_80_11__
  emel__batch__splitter__normalizing_batch --> emel__batch__splitter__normalizing_batch : emel__batch__splitter__event__normalize_batch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_77_45__
  emel__batch__splitter__normalizing_batch --> emel__batch__splitter__splitting : emel__batch__splitter__events__normalize_done [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__normalizing_batch --> emel__batch__splitter__errored : emel__batch__splitter__events__normalize_error [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_103_11__
  emel__batch__splitter__splitting --> emel__batch__splitter__splitting : emel__batch__splitter__event__create_ubatches [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_110_45__
  emel__batch__splitter__splitting --> emel__batch__splitter__publishing : emel__batch__splitter__events__split_done [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__splitting --> emel__batch__splitter__errored : emel__batch__splitter__events__split_error [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__publishing --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_126_11__
  emel__batch__splitter__publishing --> emel__batch__splitter__publishing : emel__batch__splitter__event__publish [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_326_37__
  emel__batch__splitter__publishing --> emel__batch__splitter__done : emel__batch__splitter__events__publish_done [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__publishing --> emel__batch__splitter__errored : emel__batch__splitter__events__publish_error [boost__sml__front__always] / boost__sml__front__none
  emel__batch__splitter__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_148_11__
  emel__batch__splitter__done --> emel__batch__splitter__initialized : emel__batch__splitter__events__splitting_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_332_43__
  emel__batch__splitter__done --> emel__batch__splitter__initialized : emel__batch__splitter__events__splitting_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_352_44__
  emel__batch__splitter__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_sm_hpp_175_11__
  emel__batch__splitter__errored --> emel__batch__splitter__initialized : emel__batch__splitter__events__splitting_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__batch__splitter__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_batch_splitter_actions_hpp_352_44__
