stateDiagram-v2
  [*] --> ready
  ready --> configuring : emel__buffer__chunk_allocator__event__configure [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_configure_
  configuring --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_89_11__
  configuring --> configuring : emel__buffer__chunk_allocator__event__validate_configure [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_validate_configure_
  configuring --> applying_configure : emel__buffer__chunk_allocator__events__validate_configure_done [boost__sml__front__always] / boost__sml__front__none
  configuring --> failed : emel__buffer__chunk_allocator__events__validate_configure_error [boost__sml__front__always] / boost__sml__front__none
  applying_configure --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_112_11__
  applying_configure --> applying_configure : emel__buffer__chunk_allocator__event__apply_configure [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_apply_configure_
  applying_configure --> configure_done : emel__buffer__chunk_allocator__events__apply_configure_done [boost__sml__front__always] / boost__sml__front__none
  applying_configure --> failed : emel__buffer__chunk_allocator__events__apply_configure_error [boost__sml__front__always] / boost__sml__front__none
  configure_done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_137_11__
  configure_done --> ready : emel__buffer__chunk_allocator__events__configure_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_configure_done_
  ready --> validating_allocate : emel__buffer__chunk_allocator__event__allocate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_allocate_
  validating_allocate --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_151_11__
  validating_allocate --> validating_allocate : emel__buffer__chunk_allocator__event__validate_allocate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_validate_allocate_
  validating_allocate --> selecting_block : emel__buffer__chunk_allocator__events__validate_allocate_done [boost__sml__front__always] / boost__sml__front__none
  validating_allocate --> failed : emel__buffer__chunk_allocator__events__validate_allocate_error [boost__sml__front__always] / boost__sml__front__none
  selecting_block --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_182_11__
  selecting_block --> selecting_block : emel__buffer__chunk_allocator__event__select_block [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_select_block_
  selecting_block --> ensuring_chunk : emel__buffer__chunk_allocator__events__select_block_done [boost__sml__front__always] / boost__sml__front__none
  selecting_block --> failed : emel__buffer__chunk_allocator__events__select_block_error [boost__sml__front__always] / boost__sml__front__none
  ensuring_chunk --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_206_11__
  ensuring_chunk --> ensuring_chunk : emel__buffer__chunk_allocator__event__ensure_chunk [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_ensure_chunk_
  ensuring_chunk --> committing_allocate : emel__buffer__chunk_allocator__events__ensure_chunk_done [boost__sml__front__always] / boost__sml__front__none
  ensuring_chunk --> failed : emel__buffer__chunk_allocator__events__ensure_chunk_error [boost__sml__front__always] / boost__sml__front__none
  committing_allocate --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_229_11__
  committing_allocate --> committing_allocate : emel__buffer__chunk_allocator__event__commit_allocate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_commit_allocate_
  committing_allocate --> allocate_done : emel__buffer__chunk_allocator__events__commit_allocate_done [boost__sml__front__always] / boost__sml__front__none
  committing_allocate --> failed : emel__buffer__chunk_allocator__events__commit_allocate_error [boost__sml__front__always] / boost__sml__front__none
  allocate_done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_254_11__
  allocate_done --> ready : emel__buffer__chunk_allocator__events__allocate_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_allocate_done_
  ready --> validating_release : emel__buffer__chunk_allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_release_
  validating_release --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_282_11__
  validating_release --> validating_release : emel__buffer__chunk_allocator__event__validate_release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_validate_release_
  validating_release --> merging_release : emel__buffer__chunk_allocator__events__validate_release_done [boost__sml__front__always] / boost__sml__front__none
  validating_release --> failed : emel__buffer__chunk_allocator__events__validate_release_error [boost__sml__front__always] / boost__sml__front__none
  merging_release --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_306_11__
  merging_release --> merging_release : emel__buffer__chunk_allocator__event__merge_release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_merge_release_
  merging_release --> release_done : emel__buffer__chunk_allocator__events__merge_release_done [boost__sml__front__always] / boost__sml__front__none
  merging_release --> failed : emel__buffer__chunk_allocator__events__merge_release_error [boost__sml__front__always] / boost__sml__front__none
  release_done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_330_11__
  release_done --> ready : emel__buffer__chunk_allocator__events__release_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_release_done_
  ready --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  configuring --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  applying_configure --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  configure_done --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  validating_allocate --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  selecting_block --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  ensuring_chunk --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  committing_allocate --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  allocate_done --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  validating_release --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  merging_release --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  release_done --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  failed --> resetting : emel__buffer__chunk_allocator__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__begin_reset_
  resetting --> resetting : emel__buffer__chunk_allocator__event__apply_reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__run_apply_reset_
  resetting --> reset_done : emel__buffer__chunk_allocator__events__apply_reset_done [boost__sml__front__always] / boost__sml__front__none
  resetting --> failed : emel__buffer__chunk_allocator__events__apply_reset_error [boost__sml__front__always] / boost__sml__front__none
  resetting --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_369_11__
  reset_done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_387_11__
  reset_done --> ready : emel__buffer__chunk_allocator__events__reset_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_reset_done_
  failed --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_chunk_allocator_sm_hpp_398_11__
  failed --> ready : emel__buffer__chunk_allocator__events__configure_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_configure_error_
  failed --> ready : emel__buffer__chunk_allocator__events__allocate_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_allocate_error_
  failed --> ready : emel__buffer__chunk_allocator__events__release_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_release_error_
  failed --> ready : emel__buffer__chunk_allocator__events__reset_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_reset_error_
  ready --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  configuring --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  applying_configure --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  configure_done --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  validating_allocate --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  selecting_block --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  ensuring_chunk --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  committing_allocate --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  allocate_done --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  validating_release --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  merging_release --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  release_done --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  resetting --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  reset_done --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
  failed --> failed : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__chunk_allocator__action__on_unexpected_
