stateDiagram-v2
  [*] --> uninitialized
  uninitialized --> initializing : emel__buffer__allocator__event__initialize [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__valid_initialize_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_initialize_
  uninitialized --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  initializing --> failed : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_12_38__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_initialize_error_
  initializing --> ready : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_8_34__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_initialize_done_
  ready --> reserving_n_size : emel__buffer__allocator__event__reserve_n_size [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_size_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_size_cached_
  ready --> reserving_n_size : emel__buffer__allocator__event__reserve_n_size [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_size_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_size_
  ready --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  allocated --> reserving_n_size : emel__buffer__allocator__event__reserve_n_size [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_size_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_size_cached_
  allocated --> reserving_n_size : emel__buffer__allocator__event__reserve_n_size [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_size_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_size_
  allocated --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  reserving_n_size --> failed : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_12_38__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_reserve_n_size_error_
  reserving_n_size --> ready : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_8_34__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_reserve_n_size_done_
  ready --> reserving : emel__buffer__allocator__event__reserve_n [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_cached_
  ready --> reserving : emel__buffer__allocator__event__reserve_n [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_
  ready --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  allocated --> reserving : emel__buffer__allocator__event__reserve_n [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_cached_
  allocated --> reserving : emel__buffer__allocator__event__reserve_n [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_n_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_n_
  allocated --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  ready --> reserving : emel__buffer__allocator__event__reserve [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_cached_
  ready --> reserving : emel__buffer__allocator__event__reserve [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_
  ready --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  allocated --> reserving : emel__buffer__allocator__event__reserve [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_cached_
  allocated --> reserving : emel__buffer__allocator__event__reserve [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_reserve_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_reserve_
  allocated --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  reserving --> failed : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_12_38__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_reserve_error_
  reserving --> ready : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_8_34__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_reserve_done_
  ready --> allocating_graph : emel__buffer__allocator__event__alloc_graph [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_alloc_graph_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_alloc_graph_cached_
  ready --> allocating_graph : emel__buffer__allocator__event__alloc_graph [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_alloc_graph_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_alloc_graph_
  ready --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  allocated --> allocating_graph : emel__buffer__allocator__event__alloc_graph [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_alloc_graph_cached_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_alloc_graph_cached_
  allocated --> allocating_graph : emel__buffer__allocator__event__alloc_graph [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard__can_alloc_graph_] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_alloc_graph_
  allocated --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__reject_invalid_
  allocating_graph --> failed : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_12_38__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_alloc_graph_error_
  allocating_graph --> allocated : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_8_34__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_alloc_graph_done_
  uninitialized --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_noop_
  initializing --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  ready --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  reserving_n_size --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  reserving --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  allocating_graph --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  allocated --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  failed --> releasing : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__begin_release_
  releasing --> failed : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_12_38__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_release_error_
  releasing --> uninitialized : [boost__sml__aux__zero_wrapper_emel__buffer__allocator__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_buffer_allocator_guards_hpp_8_34__] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_release_done_
  uninitialized --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  uninitialized --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  uninitialized --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  uninitialized --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  initializing --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  initializing --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  initializing --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  initializing --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  initializing --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  ready --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving_n_size --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving_n_size --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving_n_size --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving_n_size --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving_n_size --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  reserving --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocating_graph --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocating_graph --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocating_graph --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocating_graph --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocating_graph --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  allocated --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  releasing --> failed : emel__buffer__allocator__event__release [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  failed --> failed : emel__buffer__allocator__event__initialize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  failed --> failed : emel__buffer__allocator__event__reserve_n_size [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  failed --> failed : emel__buffer__allocator__event__reserve_n [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  failed --> failed : emel__buffer__allocator__event__reserve [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
  failed --> failed : emel__buffer__allocator__event__alloc_graph [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__buffer__allocator__action__on_unexpected_
