stateDiagram-v2
  [*] --> emel::decoder::initialized
  emel__decoder__initialized --> emel__decoder__validating_request : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_68_38__
  emel__decoder__validating_request --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_69_11__
  emel__decoder__validating_request --> emel__decoder__validating_request : emel__decoder__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_81_38__
  emel__decoder__validating_request --> emel__decoder__initializing_batch : emel__decoder__events__validate_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__validating_request --> emel__decoder__errored : emel__decoder__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__initializing_batch --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_96_11__
  emel__decoder__initializing_batch --> emel__decoder__initializing_batch : emel__decoder__event__initialize_batch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_90_46__
  emel__decoder__initializing_batch --> emel__decoder__updating_memory_pre : emel__decoder__events__initialize_batch_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__initializing_batch --> emel__decoder__errored : emel__decoder__events__initialize_batch_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__updating_memory_pre --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_125_11__
  emel__decoder__updating_memory_pre --> emel__decoder__updating_memory_pre : emel__decoder__event__update_memory [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_127_43__
  emel__decoder__updating_memory_pre --> emel__decoder__preparing_memory_batch_initial : emel__decoder__events__update_memory_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__updating_memory_pre --> emel__decoder__errored : emel__decoder__events__update_memory_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_initial --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_155_11__
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__preparing_memory_batch_initial : emel__decoder__event__prepare_memory_batch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_144_50__
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__reserving_output : emel__decoder__events__prepare_memory_batch_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__optimizing_memory : emel__decoder__events__prepare_memory_batch_retryable_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__errored : emel__decoder__events__prepare_memory_batch_permanent_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__optimizing_memory --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_197_11__
  emel__decoder__optimizing_memory --> emel__decoder__optimizing_memory : emel__decoder__event__optimize_memory [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_192_45__
  emel__decoder__optimizing_memory --> emel__decoder__preparing_memory_batch_retry : emel__decoder__events__optimize_memory_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__optimizing_memory --> emel__decoder__errored : emel__decoder__events__optimize_memory_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_retry --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_227_11__
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__preparing_memory_batch_retry : emel__decoder__event__prepare_memory_batch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_144_50__
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__reserving_output : emel__decoder__events__prepare_memory_batch_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__errored : emel__decoder__events__prepare_memory_batch_retryable_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__errored : emel__decoder__events__prepare_memory_batch_permanent_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__reserving_output --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_267_11__
  emel__decoder__reserving_output --> emel__decoder__reserving_output : emel__decoder__event__reserve_output [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_209_44__
  emel__decoder__reserving_output --> emel__decoder__processing_ubatch : emel__decoder__events__reserve_output_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__reserving_output --> emel__decoder__errored : emel__decoder__events__reserve_output_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__processing_ubatch --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_297_11__
  emel__decoder__processing_ubatch --> emel__decoder__processing_ubatch : emel__decoder__event__process_ubatch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_217_44__
  emel__decoder__processing_ubatch --> emel__decoder__processing_ubatch : emel__decoder__events__ubatch_done [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_7_43__] / boost__sml__front__none
  emel__decoder__processing_ubatch --> emel__decoder__finalizing_outputs : emel__decoder__events__ubatch_done [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_11_42__] / boost__sml__front__none
  emel__decoder__processing_ubatch --> emel__decoder__handling_ubatch_failure : emel__decoder__events__ubatch_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__handling_ubatch_failure --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_334_11__
  emel__decoder__handling_ubatch_failure --> emel__decoder__handling_ubatch_failure : emel__decoder__event__rollback_ubatch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_264_45__
  emel__decoder__handling_ubatch_failure --> emel__decoder__errored : emel__decoder__events__rollback_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__handling_ubatch_failure --> emel__decoder__errored : emel__decoder__events__rollback_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__finalizing_outputs --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_365_11__
  emel__decoder__finalizing_outputs --> emel__decoder__finalizing_outputs : emel__decoder__event__finalize_outputs [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_286_46__
  emel__decoder__finalizing_outputs --> emel__decoder__done : emel__decoder__events__finalize_outputs_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__finalizing_outputs --> emel__decoder__errored : emel__decoder__events__finalize_outputs_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_394_11__
  emel__decoder__done --> emel__decoder__initialized : emel__decoder__events__decoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_294_57__
  emel__decoder__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_sm_hpp_412_11__
  emel__decoder__errored --> emel__decoder__initialized : emel__decoder__events__decoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_actions_hpp_307_58__
