stateDiagram-v2
  [*] --> emel__decoder__compute_executor__initialized
  emel__decoder__compute_executor__initialized --> emel__decoder__compute_executor__validating : emel__decoder__compute_executor__event__execute [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard__valid_execute_request_] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__begin_execute_
  emel__decoder__compute_executor__initialized --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard__invalid_execute_request_] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__reject_invalid_execute_
  emel__decoder__compute_executor__validating --> emel__decoder__compute_executor__validate_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_validate_
  emel__decoder__compute_executor__validate_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__validate_decision --> emel__decoder__compute_executor__prepare_decision : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_15_34__] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_prepare_graph_
  emel__decoder__compute_executor__prepare_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__prepare_decision --> emel__decoder__compute_executor__binding_inputs : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_7_38__] / boost__sml__front__none
  emel__decoder__compute_executor__prepare_decision --> emel__decoder__compute_executor__allocating_graph : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_11_48__] / boost__sml__front__none
  emel__decoder__compute_executor__allocating_graph --> emel__decoder__compute_executor__alloc_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_alloc_graph_
  emel__decoder__compute_executor__alloc_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__alloc_decision --> emel__decoder__compute_executor__binding_inputs : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_15_34__] / boost__sml__front__none
  emel__decoder__compute_executor__binding_inputs --> emel__decoder__compute_executor__bind_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_bind_inputs_
  emel__decoder__compute_executor__bind_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__bind_decision --> emel__decoder__compute_executor__running_backend : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_15_34__] / boost__sml__front__none
  emel__decoder__compute_executor__running_backend --> emel__decoder__compute_executor__backend_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_backend_
  emel__decoder__compute_executor__backend_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__backend_decision --> emel__decoder__compute_executor__extracting_outputs : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_15_34__] / boost__sml__front__none
  emel__decoder__compute_executor__extracting_outputs --> emel__decoder__compute_executor__extract_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__run_extract_outputs_
  emel__decoder__compute_executor__extract_decision --> emel__decoder__compute_executor__errored : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_19_38__] / boost__sml__front__none
  emel__decoder__compute_executor__extract_decision --> emel__decoder__compute_executor__done : [boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_guards_hpp_15_34__] / boost__sml__front__none
  emel__decoder__compute_executor__done --> emel__decoder__compute_executor__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__mark_done_
  emel__decoder__compute_executor__errored --> emel__decoder__compute_executor__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__ensure_last_error_
  emel__decoder__compute_executor__validating --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__validate_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__prepare_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__allocating_graph --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__alloc_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__binding_inputs --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__bind_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__running_backend --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__backend_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__extracting_outputs --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__extract_decision --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__done --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
  emel__decoder__compute_executor__errored --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action__on_unexpected_
