stateDiagram-v2
  [*] --> emel::decoder::ubatch_executor::initialized
  emel::decoder::ubatch_executor::initialized --> emel::decoder::ubatch_executor::validating : emel::decoder::ubatch_executor::event::execute [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:34:39)>
  emel::decoder::ubatch_executor::validating --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:54:11)>
  emel::decoder::ubatch_executor::validating --> emel::decoder::ubatch_executor::validating : emel::decoder::ubatch_executor::event::validate [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:41:38)>
  emel::decoder::ubatch_executor::validating --> emel::decoder::ubatch_executor::preparing_memory : emel::decoder::ubatch_executor::events::validate_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::validating --> emel::decoder::ubatch_executor::errored : emel::decoder::ubatch_executor::events::validate_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::preparing_memory --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:94:11)>
  emel::decoder::ubatch_executor::preparing_memory --> emel::decoder::ubatch_executor::preparing_memory : emel::decoder::ubatch_executor::event::prepare_memory [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:51:44)>
  emel::decoder::ubatch_executor::preparing_memory --> emel::decoder::ubatch_executor::preparing_kv : emel::decoder::ubatch_executor::events::prepare_memory_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::preparing_memory --> emel::decoder::ubatch_executor::errored : emel::decoder::ubatch_executor::events::prepare_memory_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::preparing_kv --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:124:11)>
  emel::decoder::ubatch_executor::preparing_kv --> emel::decoder::ubatch_executor::preparing_kv : emel::decoder::ubatch_executor::event::prepare_kv [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:73:40)>
  emel::decoder::ubatch_executor::preparing_kv --> emel::decoder::ubatch_executor::running_compute : emel::decoder::ubatch_executor::events::prepare_kv_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::preparing_kv --> emel::decoder::ubatch_executor::errored : emel::decoder::ubatch_executor::events::prepare_kv_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::running_compute --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:153:11)>
  emel::decoder::ubatch_executor::running_compute --> emel::decoder::ubatch_executor::running_compute : emel::decoder::ubatch_executor::event::run_compute [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:83:37)>
  emel::decoder::ubatch_executor::running_compute --> emel::decoder::ubatch_executor::extracting_outputs : emel::decoder::ubatch_executor::events::run_compute_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::running_compute --> emel::decoder::ubatch_executor::rolling_back : emel::decoder::ubatch_executor::events::run_compute_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::extracting_outputs --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:183:11)>
  emel::decoder::ubatch_executor::extracting_outputs --> emel::decoder::ubatch_executor::extracting_outputs : emel::decoder::ubatch_executor::event::extract_outputs [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:118:45)>
  emel::decoder::ubatch_executor::extracting_outputs --> emel::decoder::ubatch_executor::done : emel::decoder::ubatch_executor::events::extract_outputs_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::extracting_outputs --> emel::decoder::ubatch_executor::rolling_back : emel::decoder::ubatch_executor::events::extract_outputs_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::rolling_back --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:212:11)>
  emel::decoder::ubatch_executor::rolling_back --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:238:11)>
  emel::decoder::ubatch_executor::rolling_back --> emel::decoder::ubatch_executor::rolling_back : emel::decoder::ubatch_executor::event::rollback [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:129:38)>
  emel::decoder::ubatch_executor::rolling_back --> emel::decoder::ubatch_executor::errored : emel::decoder::ubatch_executor::events::rollback_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::rolling_back --> emel::decoder::ubatch_executor::errored : emel::decoder::ubatch_executor::events::rollback_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::ubatch_executor::done --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:269:11)>
  emel::decoder::ubatch_executor::done --> emel::decoder::ubatch_executor::initialized : emel::decoder::ubatch_executor::events::ubatch_execution_done [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:145:50)>
  emel::decoder::ubatch_executor::done --> emel::decoder::ubatch_executor::initialized : emel::decoder::ubatch_executor::events::ubatch_execution_error [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:151:51)>
  emel::decoder::ubatch_executor::errored --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/sm.hpp:297:11)>
  emel::decoder::ubatch_executor::errored --> emel::decoder::ubatch_executor::initialized : emel::decoder::ubatch_executor::events::ubatch_execution_error [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::ubatch_executor::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/ubatch_executor/actions.hpp:151:51)>
