stateDiagram-v2
  [*] --> emel__decoder__compute_executor__initialized
  emel__decoder__compute_executor__initialized --> emel__decoder__compute_executor__validating : emel__decoder__compute_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_18_39__
  emel__decoder__compute_executor__validating --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_46_11__
  emel__decoder__compute_executor__validating --> emel__decoder__compute_executor__validating : emel__decoder__compute_executor__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_25_38__
  emel__decoder__compute_executor__validating --> emel__decoder__compute_executor__binding_inputs : emel__decoder__compute_executor__events__validate_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__validating --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__binding_inputs --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_73_11__
  emel__decoder__compute_executor__binding_inputs --> emel__decoder__compute_executor__binding_inputs : emel__decoder__compute_executor__event__bind_inputs [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_38_41__
  emel__decoder__compute_executor__binding_inputs --> emel__decoder__compute_executor__running_backend : emel__decoder__compute_executor__events__bind_inputs_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__binding_inputs --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__events__bind_inputs_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__running_backend --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_100_11__
  emel__decoder__compute_executor__running_backend --> emel__decoder__compute_executor__running_backend : emel__decoder__compute_executor__event__run_backend [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_43_37__
  emel__decoder__compute_executor__running_backend --> emel__decoder__compute_executor__extracting_outputs : emel__decoder__compute_executor__events__run_backend_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__running_backend --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__events__run_backend_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__extracting_outputs --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_128_11__
  emel__decoder__compute_executor__extracting_outputs --> emel__decoder__compute_executor__extracting_outputs : emel__decoder__compute_executor__event__extract_outputs [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_52_45__
  emel__decoder__compute_executor__extracting_outputs --> emel__decoder__compute_executor__done : emel__decoder__compute_executor__events__extract_outputs_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__extracting_outputs --> emel__decoder__compute_executor__errored : emel__decoder__compute_executor__events__extract_outputs_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__compute_executor__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_156_11__
  emel__decoder__compute_executor__done --> emel__decoder__compute_executor__initialized : emel__decoder__compute_executor__events__compute_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_64_41__
  emel__decoder__compute_executor__done --> emel__decoder__compute_executor__initialized : emel__decoder__compute_executor__events__compute_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_70_42__
  emel__decoder__compute_executor__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_sm_hpp_177_11__
  emel__decoder__compute_executor__errored --> emel__decoder__compute_executor__initialized : emel__decoder__compute_executor__events__compute_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__compute_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_compute_executor_actions_hpp_70_42__
