stateDiagram-v2
  [*] --> emel__decoder__ubatch_executor__initialized
  emel__decoder__ubatch_executor__initialized --> emel__decoder__ubatch_executor__validating : emel__decoder__ubatch_executor__event__execute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_34_39__
  emel__decoder__ubatch_executor__validating --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_54_11__
  emel__decoder__ubatch_executor__validating --> emel__decoder__ubatch_executor__validating : emel__decoder__ubatch_executor__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_41_38__
  emel__decoder__ubatch_executor__validating --> emel__decoder__ubatch_executor__preparing_memory : emel__decoder__ubatch_executor__events__validate_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__validating --> emel__decoder__ubatch_executor__errored : emel__decoder__ubatch_executor__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__preparing_memory --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_94_11__
  emel__decoder__ubatch_executor__preparing_memory --> emel__decoder__ubatch_executor__preparing_memory : emel__decoder__ubatch_executor__event__prepare_memory [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_51_44__
  emel__decoder__ubatch_executor__preparing_memory --> emel__decoder__ubatch_executor__preparing_kv : emel__decoder__ubatch_executor__events__prepare_memory_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__preparing_memory --> emel__decoder__ubatch_executor__errored : emel__decoder__ubatch_executor__events__prepare_memory_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__preparing_kv --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_124_11__
  emel__decoder__ubatch_executor__preparing_kv --> emel__decoder__ubatch_executor__preparing_kv : emel__decoder__ubatch_executor__event__prepare_kv [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_73_40__
  emel__decoder__ubatch_executor__preparing_kv --> emel__decoder__ubatch_executor__running_compute : emel__decoder__ubatch_executor__events__prepare_kv_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__preparing_kv --> emel__decoder__ubatch_executor__errored : emel__decoder__ubatch_executor__events__prepare_kv_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__running_compute --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_153_11__
  emel__decoder__ubatch_executor__running_compute --> emel__decoder__ubatch_executor__running_compute : emel__decoder__ubatch_executor__event__run_compute [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_83_37__
  emel__decoder__ubatch_executor__running_compute --> emel__decoder__ubatch_executor__extracting_outputs : emel__decoder__ubatch_executor__events__run_compute_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__running_compute --> emel__decoder__ubatch_executor__rolling_back : emel__decoder__ubatch_executor__events__run_compute_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__extracting_outputs --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_183_11__
  emel__decoder__ubatch_executor__extracting_outputs --> emel__decoder__ubatch_executor__extracting_outputs : emel__decoder__ubatch_executor__event__extract_outputs [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_118_45__
  emel__decoder__ubatch_executor__extracting_outputs --> emel__decoder__ubatch_executor__done : emel__decoder__ubatch_executor__events__extract_outputs_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__extracting_outputs --> emel__decoder__ubatch_executor__rolling_back : emel__decoder__ubatch_executor__events__extract_outputs_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__rolling_back --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_212_11__
  emel__decoder__ubatch_executor__rolling_back --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_238_11__
  emel__decoder__ubatch_executor__rolling_back --> emel__decoder__ubatch_executor__rolling_back : emel__decoder__ubatch_executor__event__rollback [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_129_38__
  emel__decoder__ubatch_executor__rolling_back --> emel__decoder__ubatch_executor__errored : emel__decoder__ubatch_executor__events__rollback_done [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__rolling_back --> emel__decoder__ubatch_executor__errored : emel__decoder__ubatch_executor__events__rollback_error [boost__sml__front__always] / boost__sml__front__none
  emel__decoder__ubatch_executor__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_269_11__
  emel__decoder__ubatch_executor__done --> emel__decoder__ubatch_executor__initialized : emel__decoder__ubatch_executor__events__ubatch_execution_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_145_50__
  emel__decoder__ubatch_executor__done --> emel__decoder__ubatch_executor__initialized : emel__decoder__ubatch_executor__events__ubatch_execution_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_151_51__
  emel__decoder__ubatch_executor__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_sm_hpp_297_11__
  emel__decoder__ubatch_executor__errored --> emel__decoder__ubatch_executor__initialized : emel__decoder__ubatch_executor__events__ubatch_execution_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__ubatch_executor__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_ubatch_executor_actions_hpp_151_51__
