stateDiagram-v2
  [*] --> emel::decoder::initialized
  emel::decoder::initialized --> emel::decoder::validating_request : emel::decoder::event::decode [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:68:38)>
  emel::decoder::validating_request --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:69:11)>
  emel::decoder::validating_request --> emel::decoder::validating_request : emel::decoder::event::validate [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:81:38)>
  emel::decoder::validating_request --> emel::decoder::initializing_batch : emel::decoder::events::validate_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::validating_request --> emel::decoder::errored : emel::decoder::events::validate_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::initializing_batch --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:96:11)>
  emel::decoder::initializing_batch --> emel::decoder::initializing_batch : emel::decoder::event::initialize_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:90:46)>
  emel::decoder::initializing_batch --> emel::decoder::updating_memory_pre : emel::decoder::events::initialize_batch_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::initializing_batch --> emel::decoder::errored : emel::decoder::events::initialize_batch_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::updating_memory_pre --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:125:11)>
  emel::decoder::updating_memory_pre --> emel::decoder::updating_memory_pre : emel::decoder::event::update_memory [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:127:43)>
  emel::decoder::updating_memory_pre --> emel::decoder::preparing_memory_batch_initial : emel::decoder::events::update_memory_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::updating_memory_pre --> emel::decoder::errored : emel::decoder::events::update_memory_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_initial --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:155:11)>
  emel::decoder::preparing_memory_batch_initial --> emel::decoder::preparing_memory_batch_initial : emel::decoder::event::prepare_memory_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:144:50)>
  emel::decoder::preparing_memory_batch_initial --> emel::decoder::reserving_output : emel::decoder::events::prepare_memory_batch_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_initial --> emel::decoder::optimizing_memory : emel::decoder::events::prepare_memory_batch_retryable_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_initial --> emel::decoder::errored : emel::decoder::events::prepare_memory_batch_permanent_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::optimizing_memory --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:197:11)>
  emel::decoder::optimizing_memory --> emel::decoder::optimizing_memory : emel::decoder::event::optimize_memory [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:192:45)>
  emel::decoder::optimizing_memory --> emel::decoder::preparing_memory_batch_retry : emel::decoder::events::optimize_memory_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::optimizing_memory --> emel::decoder::errored : emel::decoder::events::optimize_memory_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_retry --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:227:11)>
  emel::decoder::preparing_memory_batch_retry --> emel::decoder::preparing_memory_batch_retry : emel::decoder::event::prepare_memory_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:144:50)>
  emel::decoder::preparing_memory_batch_retry --> emel::decoder::reserving_output : emel::decoder::events::prepare_memory_batch_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_retry --> emel::decoder::errored : emel::decoder::events::prepare_memory_batch_retryable_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::preparing_memory_batch_retry --> emel::decoder::errored : emel::decoder::events::prepare_memory_batch_permanent_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::reserving_output --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:267:11)>
  emel::decoder::reserving_output --> emel::decoder::reserving_output : emel::decoder::event::reserve_output [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:209:44)>
  emel::decoder::reserving_output --> emel::decoder::processing_ubatch : emel::decoder::events::reserve_output_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::reserving_output --> emel::decoder::errored : emel::decoder::events::reserve_output_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::processing_ubatch --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:297:11)>
  emel::decoder::processing_ubatch --> emel::decoder::processing_ubatch : emel::decoder::event::process_ubatch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:217:44)>
  emel::decoder::processing_ubatch --> emel::decoder::processing_ubatch : emel::decoder::events::ubatch_done [boost::sml::aux::zero_wrapper<emel::decoder::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/guards.hpp:7:43)>] / boost::sml::front::none
  emel::decoder::processing_ubatch --> emel::decoder::finalizing_outputs : emel::decoder::events::ubatch_done [boost::sml::aux::zero_wrapper<emel::decoder::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/guards.hpp:11:42)>] / boost::sml::front::none
  emel::decoder::processing_ubatch --> emel::decoder::handling_ubatch_failure : emel::decoder::events::ubatch_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::handling_ubatch_failure --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:334:11)>
  emel::decoder::handling_ubatch_failure --> emel::decoder::handling_ubatch_failure : emel::decoder::event::rollback_ubatch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:264:45)>
  emel::decoder::handling_ubatch_failure --> emel::decoder::errored : emel::decoder::events::rollback_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::handling_ubatch_failure --> emel::decoder::errored : emel::decoder::events::rollback_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::finalizing_outputs --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:365:11)>
  emel::decoder::finalizing_outputs --> emel::decoder::finalizing_outputs : emel::decoder::event::finalize_outputs [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:286:46)>
  emel::decoder::finalizing_outputs --> emel::decoder::done : emel::decoder::events::finalize_outputs_done [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::finalizing_outputs --> emel::decoder::errored : emel::decoder::events::finalize_outputs_error [boost::sml::front::always] / boost::sml::front::none
  emel::decoder::done --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:394:11)>
  emel::decoder::done --> emel::decoder::initialized : emel::decoder::events::decoding_done [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:294:57)>
  emel::decoder::errored --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/sm.hpp:412:11)>
  emel::decoder::errored --> emel::decoder::initialized : emel::decoder::events::decoding_error [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::decoder::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/decoder/actions.hpp:307:58)>
