stateDiagram-v2
  [*] --> emel__decoder__initialized
  emel__decoder__initialized --> emel__decoder__validating_request : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__begin_decode_
  emel__decoder__validating_request --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_61_46__] / boost__sml__aux__zero_wrapper_emel__decoder__action__reject_invalid_validate_
  emel__decoder__validating_request --> emel__decoder__validate_decision : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_26_44__] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_validate_
  emel__decoder__validate_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__validate_decision --> emel__decoder__initializing_batch : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__initializing_batch --> emel__decoder__initialize_batch_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_initialize_batch_
  emel__decoder__initialize_batch_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__initialize_batch_decision --> emel__decoder__updating_memory_pre : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__updating_memory_pre --> emel__decoder__update_memory_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_update_memory_
  emel__decoder__update_memory_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__update_memory_decision --> emel__decoder__preparing_memory_batch_initial : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__prepare_memory_batch_initial_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_prepare_memory_batch_
  emel__decoder__prepare_memory_batch_initial_decision --> emel__decoder__optimizing_memory : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_113_48__] / boost__sml__front__none
  emel__decoder__prepare_memory_batch_initial_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_117_48__] / boost__sml__front__none
  emel__decoder__prepare_memory_batch_initial_decision --> emel__decoder__reserving_output : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__optimizing_memory --> emel__decoder__optimize_memory_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_optimize_memory_
  emel__decoder__optimize_memory_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__optimize_memory_decision --> emel__decoder__preparing_memory_batch_retry : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__prepare_memory_batch_retry_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_prepare_memory_batch_
  emel__decoder__prepare_memory_batch_retry_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__prepare_memory_batch_retry_decision --> emel__decoder__reserving_output : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__reserving_output --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_69_47__] / boost__sml__aux__zero_wrapper_emel__decoder__action__reject_invalid_reserve_output_
  emel__decoder__reserving_output --> emel__decoder__reserve_decision : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_65_45__] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_reserve_output_
  emel__decoder__reserve_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__reserve_decision --> emel__decoder__processing_ubatch : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__processing_ubatch --> emel__decoder__finalizing_outputs : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_11_42__] / boost__sml__front__none
  emel__decoder__processing_ubatch --> emel__decoder__ubatch_decision : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_85_47__] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_invalid_ubatch_size_
  emel__decoder__processing_ubatch --> emel__decoder__ubatch_decision : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_81_44__] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_process_ubatch_
  emel__decoder__ubatch_decision --> emel__decoder__handling_ubatch_failure : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__ubatch_decision --> emel__decoder__processing_ubatch : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__handling_ubatch_failure --> emel__decoder__rollback_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_rollback_ubatch_
  emel__decoder__rollback_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__aux__zero_wrapper_emel__decoder__action__capture_rollback_error_
  emel__decoder__rollback_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__aux__zero_wrapper_emel__decoder__action__capture_ubatch_error_
  emel__decoder__finalizing_outputs --> emel__decoder__finalize_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__run_finalize_outputs_
  emel__decoder__finalize_decision --> emel__decoder__errored : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_101_38__] / boost__sml__front__none
  emel__decoder__finalize_decision --> emel__decoder__done : [boost__sml__aux__zero_wrapper_emel__decoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_decoder_guards_hpp_97_34__] / boost__sml__front__none
  emel__decoder__done --> emel__decoder__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__mark_done_
  emel__decoder__errored --> emel__decoder__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__ensure_last_error_
  emel__decoder__validating_request --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__validate_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__initializing_batch --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__initialize_batch_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__updating_memory_pre --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__update_memory_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__preparing_memory_batch_initial --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__prepare_memory_batch_initial_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__optimizing_memory --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__optimize_memory_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__preparing_memory_batch_retry --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__prepare_memory_batch_retry_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__reserving_output --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__reserve_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__processing_ubatch --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__ubatch_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__handling_ubatch_failure --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__rollback_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__finalizing_outputs --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__finalize_decision --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__done --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
  emel__decoder__errored --> emel__decoder__errored : emel__decoder__event__decode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__decoder__action__on_unexpected_
