stateDiagram-v2
  direction TB
  [*] --> state_uninitialized
  state_uninitialized --> state_initializing : initialize_run [guard_valid_initialize_] / effect_begin_initialize_
  state_uninitialized --> state_initialize_publish_error : initialize_run [guard_invalid_initialize_] / effect_reject_initialize_
  state_idle --> state_initializing : initialize_run [guard_valid_initialize_] / effect_begin_initialize_
  state_idle --> state_initialize_publish_error : initialize_run [guard_invalid_initialize_] / effect_reject_initialize_
  state_idle --> state_conditioning : embed_text_run [guard_valid_embed_full_] / effect_begin_embed_text_
  state_idle --> state_conditioning : embed_text_run [guard_valid_embed_truncate_] / effect_begin_embed_text_
  state_idle --> state_embed_publish_error : embed_text_run [guard_invalid_embed_] / effect_reject_embed_text_
  state_idle --> state_image_preparing : embed_image_run [guard_valid_embed_image_full_] / effect_begin_embed_image_
  state_idle --> state_image_preparing : embed_image_run [guard_valid_embed_image_truncate_] / effect_begin_embed_image_
  state_idle --> state_embed_publish_error : embed_image_run [guard_invalid_embed_image_] / effect_reject_embed_image_
  state_idle --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_full_] / effect_begin_embed_audio_
  state_idle --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_truncate_] / effect_begin_embed_audio_
  state_idle --> state_embed_publish_error : embed_audio_run [guard_invalid_embed_audio_] / effect_reject_embed_audio_
  state_done --> state_initializing : initialize_run [guard_valid_initialize_] / effect_begin_initialize_
  state_done --> state_initialize_publish_error : initialize_run [guard_invalid_initialize_] / effect_reject_initialize_
  state_done --> state_conditioning : embed_text_run [guard_valid_embed_full_] / effect_begin_embed_text_
  state_done --> state_conditioning : embed_text_run [guard_valid_embed_truncate_] / effect_begin_embed_text_
  state_done --> state_embed_publish_error : embed_text_run [guard_invalid_embed_] / effect_reject_embed_text_
  state_done --> state_image_preparing : embed_image_run [guard_valid_embed_image_full_] / effect_begin_embed_image_
  state_done --> state_image_preparing : embed_image_run [guard_valid_embed_image_truncate_] / effect_begin_embed_image_
  state_done --> state_embed_publish_error : embed_image_run [guard_invalid_embed_image_] / effect_reject_embed_image_
  state_done --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_full_] / effect_begin_embed_audio_
  state_done --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_truncate_] / effect_begin_embed_audio_
  state_done --> state_embed_publish_error : embed_audio_run [guard_invalid_embed_audio_] / effect_reject_embed_audio_
  state_errored --> state_initializing : initialize_run [guard_valid_initialize_] / effect_begin_initialize_
  state_errored --> state_initialize_publish_error : initialize_run [guard_invalid_initialize_] / effect_reject_initialize_
  state_errored --> state_conditioning : embed_text_run [guard_valid_embed_full_] / effect_begin_embed_text_
  state_errored --> state_conditioning : embed_text_run [guard_valid_embed_truncate_] / effect_begin_embed_text_
  state_errored --> state_embed_publish_error : embed_text_run [guard_invalid_embed_] / effect_reject_embed_text_
  state_errored --> state_image_preparing : embed_image_run [guard_valid_embed_image_full_] / effect_begin_embed_image_
  state_errored --> state_image_preparing : embed_image_run [guard_valid_embed_image_truncate_] / effect_begin_embed_image_
  state_errored --> state_embed_publish_error : embed_image_run [guard_invalid_embed_image_] / effect_reject_embed_image_
  state_errored --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_full_] / effect_begin_embed_audio_
  state_errored --> state_audio_preparing : embed_audio_run [guard_valid_embed_audio_truncate_] / effect_begin_embed_audio_
  state_errored --> state_embed_publish_error : embed_audio_run [guard_invalid_embed_audio_] / effect_reject_embed_audio_
  state_initializing --> state_initialize_decision : completion_initialize_run_ [always] / effect_dispatch_bind_conditioner_
  state_initialize_decision --> state_initialize_publish_success : completion_initialize_run_ [guard_initialize_success_] / effect_mark_initialized_
  state_initialize_decision --> state_initialize_publish_error : completion_initialize_run_ [guard_initialize_model_invalid_] / effect_set_initialize_model_invalid_
  state_initialize_decision --> state_initialize_publish_error : completion_initialize_run_ [guard_initialize_backend_error_] / effect_set_initialize_backend_error_
  state_initialize_publish_success --> state_idle : completion_initialize_run_ [guard_has_initialize_done_callback_] / effect_emit_initialize_done_
  state_initialize_publish_success --> state_idle : completion_initialize_run_ [guard_no_initialize_done_callback_] / none
  state_initialize_publish_error --> state_initialize_error_channel_decision : completion_initialize_run_ [always] / effect_write_initialize_error_out_
  state_initialize_error_channel_decision --> state_errored : completion_initialize_run_ [guard_has_initialize_error_callback_] / effect_emit_initialize_error_
  state_initialize_error_channel_decision --> state_errored : completion_initialize_run_ [guard_no_initialize_error_callback_] / none
  state_conditioning --> state_conditioning_decision : completion_embed_text_run_ [always] / effect_dispatch_condition_text_
  state_conditioning_decision --> state_embed_publish_error : completion_embed_text_run_ [guard_prepare_invalid_request_] / effect_set_embed_invalid_request_
  state_conditioning_decision --> state_embed_publish_error : completion_embed_text_run_ [guard_prepare_model_invalid_] / effect_set_embed_model_invalid_
  state_conditioning_decision --> state_embed_publish_error : completion_embed_text_run_ [guard_prepare_backend_error_] / effect_set_embed_backend_error_
  state_conditioning_decision --> state_encoding : completion_embed_text_run_ [guard_prepare_success_] / none
  state_encoding --> state_embedding_decision : completion_embed_text_run_ [always] / effect_run_text_embedding_
  state_embedding_decision --> state_embed_publish_error : completion_embed_text_run_ [guard_embedding_failed_] / none
  state_embedding_decision --> state_embed_publish_success : completion_embed_text_run_ [guard_embedding_succeeded_full_] / effect_publish_full_embedding_
  state_embedding_decision --> state_embed_publish_success : completion_embed_text_run_ [guard_embedding_succeeded_truncate_] / effect_publish_truncated_embedding_
  state_embed_publish_success --> state_done : completion_embed_text_run_ [guard_has_embed_done_callback_] / effect_emit_embed_done_
  state_embed_publish_success --> state_done : completion_embed_text_run_ [guard_no_embed_done_callback_] / none
  state_embed_publish_error --> state_embed_error_channel_decision : completion_embed_text_run_ [always] / effect_write_embed_error_out_
  state_embed_error_channel_decision --> state_errored : completion_embed_text_run_ [guard_has_embed_error_callback_] / effect_emit_embed_error_
  state_embed_error_channel_decision --> state_errored : completion_embed_text_run_ [guard_no_embed_error_callback_] / none
  state_image_preparing --> state_image_preparing_decision : completion_embed_image_run_ [always] / effect_prepare_image_input_
  state_image_preparing_decision --> state_embed_publish_error : completion_embed_image_run_ [guard_image_prepare_backend_error_] / effect_set_embed_backend_error_
  state_image_preparing_decision --> state_image_encoding : completion_embed_image_run_ [guard_image_prepare_success_] / none
  state_image_encoding --> state_embedding_decision : completion_embed_image_run_ [always] / effect_run_image_embedding_
  state_embedding_decision --> state_embed_publish_error : completion_embed_image_run_ [guard_embedding_failed_] / none
  state_embedding_decision --> state_embed_publish_success : completion_embed_image_run_ [guard_embedding_succeeded_full_] / effect_publish_full_embedding_
  state_embedding_decision --> state_embed_publish_success : completion_embed_image_run_ [guard_embedding_succeeded_truncate_] / effect_publish_truncated_embedding_
  state_embed_publish_success --> state_done : completion_embed_image_run_ [guard_has_embed_done_callback_] / effect_emit_embed_done_
  state_embed_publish_success --> state_done : completion_embed_image_run_ [guard_no_embed_done_callback_] / none
  state_embed_publish_error --> state_embed_error_channel_decision : completion_embed_image_run_ [always] / effect_write_embed_error_out_
  state_embed_error_channel_decision --> state_errored : completion_embed_image_run_ [guard_has_embed_error_callback_] / effect_emit_embed_error_
  state_embed_error_channel_decision --> state_errored : completion_embed_image_run_ [guard_no_embed_error_callback_] / none
  state_audio_preparing --> state_audio_preparing_decision : completion_embed_audio_run_ [always] / effect_prepare_audio_input_
  state_audio_preparing_decision --> state_embed_publish_error : completion_embed_audio_run_ [guard_audio_prepare_backend_error_] / effect_set_embed_backend_error_
  state_audio_preparing_decision --> state_audio_encoding : completion_embed_audio_run_ [guard_audio_prepare_success_] / none
  state_audio_encoding --> state_embedding_decision : completion_embed_audio_run_ [always] / effect_run_audio_embedding_
  state_embedding_decision --> state_embed_publish_error : completion_embed_audio_run_ [guard_embedding_failed_] / none
  state_embedding_decision --> state_embed_publish_success : completion_embed_audio_run_ [guard_embedding_succeeded_full_] / effect_publish_full_embedding_
  state_embedding_decision --> state_embed_publish_success : completion_embed_audio_run_ [guard_embedding_succeeded_truncate_] / effect_publish_truncated_embedding_
  state_embed_publish_success --> state_done : completion_embed_audio_run_ [guard_has_embed_done_callback_] / effect_emit_embed_done_
  state_embed_publish_success --> state_done : completion_embed_audio_run_ [guard_no_embed_done_callback_] / none
  state_embed_publish_error --> state_embed_error_channel_decision : completion_embed_audio_run_ [always] / effect_write_embed_error_out_
  state_embed_error_channel_decision --> state_errored : completion_embed_audio_run_ [guard_has_embed_error_callback_] / effect_emit_embed_error_
  state_embed_error_channel_decision --> state_errored : completion_embed_audio_run_ [guard_no_embed_error_callback_] / none
  state_uninitialized --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_initializing --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_initialize_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_initialize_publish_success --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_initialize_publish_error --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_initialize_error_channel_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_idle --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_conditioning --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_conditioning_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_encoding --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_image_preparing --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_image_preparing_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_image_encoding --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_audio_preparing --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_audio_preparing_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_audio_encoding --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_embedding_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_embed_publish_success --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_embed_publish_error --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_embed_error_channel_decision --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_done --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_errored --> state_unexpected : _ [always] / effect_ignore_unexpected_
  state_unexpected --> state_unexpected : _ [always] / effect_ignore_unexpected_
