stateDiagram-v2
  [*] --> emel__encoder__wpm__initialized
  emel__encoder__wpm__initialized --> emel__encoder__wpm__encoding : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__valid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__begin_encode_
  emel__encoder__wpm__initialized --> emel__encoder__wpm__errored : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__invalid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__reject_invalid_encode_
  emel__encoder__wpm__done --> emel__encoder__wpm__encoding : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__valid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__begin_encode_
  emel__encoder__wpm__done --> emel__encoder__wpm__errored : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__invalid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__reject_invalid_encode_
  emel__encoder__wpm__errored --> emel__encoder__wpm__encoding : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__valid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__begin_encode_
  emel__encoder__wpm__errored --> emel__encoder__wpm__errored : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__invalid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__reject_invalid_encode_
  emel__encoder__wpm__unexpected --> emel__encoder__wpm__encoding : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__valid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__begin_encode_
  emel__encoder__wpm__unexpected --> emel__encoder__wpm__unexpected : emel__encoder__event__encode [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__invalid_encode_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__reject_invalid_encode_
  emel__encoder__wpm__encoding --> emel__encoder__wpm__encode_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__run_encode_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__done : [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__mark_done_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__errored : [boost__sml__aux__zero_wrapper_emel__encoder__wpm__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__ensure_last_error_
  emel__encoder__wpm__encoding --> emel__encoder__wpm__unexpected : emel__encoder__event__encode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__unexpected : emel__encoder__event__encode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__initialized --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__initialized --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encoding --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encoding --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__done --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__done --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__errored --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__errored --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__unexpected --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__unexpected --> emel__encoder__wpm__unexpected : emel__encoder__events__encoding_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__initialized --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encoding --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__encode_decision --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__done --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__errored --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
  emel__encoder__wpm__unexpected --> emel__encoder__wpm__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__wpm__action__on_unexpected_
