stateDiagram-v2
  [*] --> initialized
  initialized --> pretokenizing : emel__encoder__event__encode [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_5_45__
  pretokenizing --> selecting_algorithm : emel__encoder__event__pretokenizing_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_6_47__
  pretokenizing --> errored : emel__encoder__event__pretokenizing_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_7_48__
  selecting_algorithm --> merging : emel__encoder__event__algorithm_selected [boost__sml__aux__zero_wrapper_emel__encoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_guards_hpp_9_37__] / boost__sml__front__none
  selecting_algorithm --> searching : emel__encoder__event__algorithm_selected [boost__sml__aux__zero_wrapper_emel__encoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_guards_hpp_12_39__] / boost__sml__front__none
  selecting_algorithm --> scanning : emel__encoder__event__algorithm_selected [boost__sml__aux__zero_wrapper_emel__encoder__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_guards_hpp_15_38__] / boost__sml__front__none
  merging --> emitting_tokens : emel__encoder__event__algorithm_step_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_8_48__
  merging --> errored : emel__encoder__event__algorithm_step_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_9_49__
  searching --> emitting_tokens : emel__encoder__event__algorithm_step_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_8_48__
  searching --> errored : emel__encoder__event__algorithm_step_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_9_49__
  scanning --> emitting_tokens : emel__encoder__event__algorithm_step_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_8_48__
  scanning --> errored : emel__encoder__event__algorithm_step_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_9_49__
  emitting_tokens --> applying_backend_postrules : emel__encoder__event__emission_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_10_42__
  emitting_tokens --> errored : emel__encoder__event__emission_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_11_43__
  applying_backend_postrules --> done : emel__encoder__event__postrules_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_12_43__
  applying_backend_postrules --> errored : emel__encoder__event__postrules_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_13_44__
  done --> done : emel__encoder__event__tokenized_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_14_57__
  errored --> errored : emel__encoder__event__tokenized_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__encoder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_encoder_actions_hpp_15_58__
