stateDiagram-v2
  [*] --> emel__jinja__parser__initialized
  emel__jinja__parser__initialized --> emel__jinja__parser__parse_decision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__initialized --> emel__jinja__parser__errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__done --> emel__jinja__parser__parse_decision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__done --> emel__jinja__parser__errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__errored --> emel__jinja__parser__parse_decision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__errored --> emel__jinja__parser__errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__unexpected --> emel__jinja__parser__parse_decision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__unexpected --> emel__jinja__parser__unexpected : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__parse_decision --> emel__jinja__parser__done : [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__phase_ok_] / boost__sml__front__none
  emel__jinja__parser__parse_decision --> emel__jinja__parser__errored : [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__phase_failed_] / boost__sml__front__none
  emel__jinja__parser__initialized --> emel__jinja__parser__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__parse_decision --> emel__jinja__parser__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__done --> emel__jinja__parser__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__errored --> emel__jinja__parser__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__unexpected --> emel__jinja__parser__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
