stateDiagram-v2
  [*] --> emel__jinja__parser__Initialized
  emel__jinja__parser__Initialized --> emel__jinja__parser__ParseDecision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__Initialized --> emel__jinja__parser__Errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__Done --> emel__jinja__parser__ParseDecision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__Done --> emel__jinja__parser__Errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__Errored --> emel__jinja__parser__ParseDecision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__Errored --> emel__jinja__parser__Errored : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__Unexpected --> emel__jinja__parser__ParseDecision : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__valid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__run_parse_
  emel__jinja__parser__Unexpected --> emel__jinja__parser__Unexpected : emel__jinja__event__parse [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__invalid_parse_] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__reject_invalid_parse_
  emel__jinja__parser__ParseDecision --> emel__jinja__parser__Done : [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__phase_ok_] / boost__sml__front__none
  emel__jinja__parser__ParseDecision --> emel__jinja__parser__Errored : [boost__sml__aux__zero_wrapper_emel__jinja__parser__guard__phase_failed_] / boost__sml__front__none
  emel__jinja__parser__Initialized --> emel__jinja__parser__Unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__ParseDecision --> emel__jinja__parser__Unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__Done --> emel__jinja__parser__Unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__Errored --> emel__jinja__parser__Unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
  emel__jinja__parser__Unexpected --> emel__jinja__parser__Unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__parser__action__on_unexpected_
