stateDiagram-v2
  [*] --> emel__jinja__renderer__initialized
  emel__jinja__renderer__initialized --> emel__jinja__renderer__setup : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_8_38__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__begin_render_
  emel__jinja__renderer__initialized --> emel__jinja__renderer__errored : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_12_40__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__reject_invalid_render_
  emel__jinja__renderer__done --> emel__jinja__renderer__setup : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_8_38__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__begin_render_
  emel__jinja__renderer__done --> emel__jinja__renderer__errored : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_12_40__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__reject_invalid_render_
  emel__jinja__renderer__errored --> emel__jinja__renderer__setup : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_8_38__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__begin_render_
  emel__jinja__renderer__errored --> emel__jinja__renderer__errored : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_12_40__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__reject_invalid_render_
  emel__jinja__renderer__unexpected --> emel__jinja__renderer__setup : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_8_38__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__begin_render_
  emel__jinja__renderer__unexpected --> emel__jinja__renderer__unexpected : emel__jinja__event__render [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_jinja_renderer_guards_hpp_12_40__] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__reject_invalid_render_
  emel__jinja__renderer__setup --> emel__jinja__renderer__eval_stmt : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__seed_program_
  emel__jinja__renderer__eval_stmt --> emel__jinja__renderer__render_decision : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__phase_failed_] / boost__sml__front__none
  emel__jinja__renderer__eval_stmt --> emel__jinja__renderer__eval_expr : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__needs_expr_] / boost__sml__front__none
  emel__jinja__renderer__eval_stmt --> emel__jinja__renderer__eval_stmt : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__has_stmt_work_] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__eval_next_stmt_
  emel__jinja__renderer__eval_stmt --> emel__jinja__renderer__render_decision : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__no_stmt_work_] / boost__sml__front__none
  emel__jinja__renderer__eval_expr --> emel__jinja__renderer__eval_expr : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__has_pending_expr_] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__eval_pending_expr_
  emel__jinja__renderer__eval_expr --> emel__jinja__renderer__render_decision : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__phase_failed_] / boost__sml__front__none
  emel__jinja__renderer__eval_expr --> emel__jinja__renderer__write_output : [boost__sml__front__always] / boost__sml__front__none
  emel__jinja__renderer__write_output --> emel__jinja__renderer__render_decision : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__phase_failed_] / boost__sml__front__none
  emel__jinja__renderer__write_output --> emel__jinja__renderer__write_output : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__needs_write_] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__write_pending_value_
  emel__jinja__renderer__write_output --> emel__jinja__renderer__eval_stmt : [boost__sml__front__always] / boost__sml__front__none
  emel__jinja__renderer__render_decision --> emel__jinja__renderer__done : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__finalize_done_
  emel__jinja__renderer__render_decision --> emel__jinja__renderer__errored : [boost__sml__aux__zero_wrapper_emel__jinja__renderer__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__finalize_error_
  emel__jinja__renderer__initialized --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__setup --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__eval_stmt --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__eval_expr --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__write_output --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__render_decision --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__done --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__errored --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
  emel__jinja__renderer__unexpected --> emel__jinja__renderer__unexpected : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__jinja__renderer__action__on_unexpected_
