stateDiagram-v2
  [*] --> emel::memory::coordinator::initialized
  emel::memory::coordinator::initialized --> emel::memory::coordinator::validating_update : emel::memory::coordinator::event::prepare_update [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:17:46)>
  emel::memory::coordinator::initialized --> emel::memory::coordinator::validating_batch : emel::memory::coordinator::event::prepare_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:22:45)>
  emel::memory::coordinator::initialized --> emel::memory::coordinator::validating_full : emel::memory::coordinator::event::prepare_full [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:27:44)>
  emel::memory::coordinator::validating_update --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:69:11)>
  emel::memory::coordinator::validating_update --> emel::memory::coordinator::validating_update : emel::memory::coordinator::event::validate_update [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:33:45)>
  emel::memory::coordinator::validating_update --> emel::memory::coordinator::preparing_update : emel::memory::coordinator::events::validate_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::validating_update --> emel::memory::coordinator::errored : emel::memory::coordinator::events::validate_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::validating_batch --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:96:11)>
  emel::memory::coordinator::validating_batch --> emel::memory::coordinator::validating_batch : emel::memory::coordinator::event::validate_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:41:44)>
  emel::memory::coordinator::validating_batch --> emel::memory::coordinator::preparing_batch : emel::memory::coordinator::events::validate_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::validating_batch --> emel::memory::coordinator::errored : emel::memory::coordinator::events::validate_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::validating_full --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:123:11)>
  emel::memory::coordinator::validating_full --> emel::memory::coordinator::validating_full : emel::memory::coordinator::event::validate_full [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:53:43)>
  emel::memory::coordinator::validating_full --> emel::memory::coordinator::preparing_full : emel::memory::coordinator::events::validate_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::validating_full --> emel::memory::coordinator::errored : emel::memory::coordinator::events::validate_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::preparing_update --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:150:11)>
  emel::memory::coordinator::preparing_update --> emel::memory::coordinator::preparing_update : emel::memory::coordinator::event::prepare_update_step [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:61:49)>
  emel::memory::coordinator::preparing_update --> emel::memory::coordinator::applying_update : emel::memory::coordinator::events::prepare_done [boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:53:31)>] / boost::sml::front::none
  emel::memory::coordinator::preparing_update --> emel::memory::coordinator::publishing_update : emel::memory::coordinator::events::prepare_done [boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:56:33)>] / boost::sml::front::none
  emel::memory::coordinator::preparing_update --> emel::memory::coordinator::errored : emel::memory::coordinator::events::prepare_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::preparing_batch --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:194:11)>
  emel::memory::coordinator::preparing_batch --> emel::memory::coordinator::preparing_batch : emel::memory::coordinator::event::prepare_batch_step [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:73:48)>
  emel::memory::coordinator::preparing_batch --> emel::memory::coordinator::publishing_batch : emel::memory::coordinator::events::prepare_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::preparing_batch --> emel::memory::coordinator::errored : emel::memory::coordinator::events::prepare_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::preparing_full --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:226:11)>
  emel::memory::coordinator::preparing_full --> emel::memory::coordinator::preparing_full : emel::memory::coordinator::event::prepare_full_step [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:86:47)>
  emel::memory::coordinator::preparing_full --> emel::memory::coordinator::publishing_full : emel::memory::coordinator::events::prepare_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::preparing_full --> emel::memory::coordinator::errored : emel::memory::coordinator::events::prepare_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::applying_update --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:258:11)>
  emel::memory::coordinator::applying_update --> emel::memory::coordinator::applying_update : emel::memory::coordinator::event::apply_update_step [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:99:47)>
  emel::memory::coordinator::applying_update --> emel::memory::coordinator::publishing_update : emel::memory::coordinator::events::apply_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::applying_update --> emel::memory::coordinator::errored : emel::memory::coordinator::events::apply_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_update --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:289:11)>
  emel::memory::coordinator::publishing_update --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:315:11)>
  emel::memory::coordinator::publishing_update --> emel::memory::coordinator::publishing_update : emel::memory::coordinator::event::publish_update [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:121:44)>
  emel::memory::coordinator::publishing_update --> emel::memory::coordinator::done : emel::memory::coordinator::events::publish_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_update --> emel::memory::coordinator::errored : emel::memory::coordinator::events::publish_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_batch --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:346:11)>
  emel::memory::coordinator::publishing_batch --> emel::memory::coordinator::publishing_batch : emel::memory::coordinator::event::publish_batch [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:129:43)>
  emel::memory::coordinator::publishing_batch --> emel::memory::coordinator::done : emel::memory::coordinator::events::publish_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_batch --> emel::memory::coordinator::errored : emel::memory::coordinator::events::publish_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_full --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:377:11)>
  emel::memory::coordinator::publishing_full --> emel::memory::coordinator::publishing_full : emel::memory::coordinator::event::publish_full [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:137:42)>
  emel::memory::coordinator::publishing_full --> emel::memory::coordinator::done : emel::memory::coordinator::events::publish_done [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::publishing_full --> emel::memory::coordinator::errored : emel::memory::coordinator::events::publish_error [boost::sml::front::always] / boost::sml::front::none
  emel::memory::coordinator::done --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:408:11)>
  emel::memory::coordinator::done --> emel::memory::coordinator::initialized : emel::memory::coordinator::events::memory_done [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:145:40)>
  emel::memory::coordinator::done --> emel::memory::coordinator::initialized : emel::memory::coordinator::events::memory_error [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:146:41)>
  emel::memory::coordinator::errored --> boost::sml::front::internal : on_entry [boost::sml::front::always] / boost::sml::aux::zero_wrapper<(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/sm.hpp:422:11)>
  emel::memory::coordinator::errored --> emel::memory::coordinator::initialized : emel::memory::coordinator::events::memory_error [boost::sml::front::always] / boost::sml::aux::zero_wrapper<emel::memory::coordinator::action::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/memory/coordinator/actions.hpp:146:41)>
