stateDiagram-v2
  [*] --> emel__memory__coordinator__hybrid__initialized
  emel__memory__coordinator__hybrid__initialized --> emel__memory__coordinator__hybrid__validating_update : emel__memory__coordinator__event__prepare_update [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_35_46__
  emel__memory__coordinator__hybrid__initialized --> emel__memory__coordinator__hybrid__validating_batch : emel__memory__coordinator__event__prepare_batch [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_46_45__
  emel__memory__coordinator__hybrid__initialized --> emel__memory__coordinator__hybrid__validating_full : emel__memory__coordinator__event__prepare_full [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_57_44__
  emel__memory__coordinator__hybrid__validating_update --> emel__memory__coordinator__hybrid__preparing_update : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_update_context_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__validating_update --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_update_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__validating_batch --> emel__memory__coordinator__hybrid__preparing_batch : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_batch_context_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__validating_batch --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_batch_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__validating_full --> emel__memory__coordinator__hybrid__preparing_full : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_full_context_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__validating_full --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_full_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__preparing_update --> emel__memory__coordinator__hybrid__prepare_update_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_78_50__
  emel__memory__coordinator__hybrid__prepare_update_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__prepare_update_decision --> emel__memory__coordinator__hybrid__applying_update : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__prepare_update_success_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__prepare_update_decision --> emel__memory__coordinator__hybrid__publishing_update : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__prepare_update_no_update_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__prepare_update_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__prepare_update_invalid_status_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_73_43__
  emel__memory__coordinator__hybrid__preparing_batch --> emel__memory__coordinator__hybrid__prepare_batch_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_85_49__
  emel__memory__coordinator__hybrid__prepare_batch_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__prepare_batch_decision --> emel__memory__coordinator__hybrid__publishing_batch : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__preparing_full --> emel__memory__coordinator__hybrid__prepare_full_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_92_48__
  emel__memory__coordinator__hybrid__prepare_full_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__prepare_full_decision --> emel__memory__coordinator__hybrid__publishing_full : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__applying_update --> emel__memory__coordinator__hybrid__apply_update_decision : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__apply_update_ready_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_99_48__
  emel__memory__coordinator__hybrid__applying_update --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__apply_update_backend_failed_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_73_43__
  emel__memory__coordinator__hybrid__applying_update --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__apply_update_invalid_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__apply_update_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__apply_update_decision --> emel__memory__coordinator__hybrid__publishing_update : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publishing_update --> emel__memory__coordinator__hybrid__publish_update_decision : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_publish_update_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_105_50__
  emel__memory__coordinator__hybrid__publishing_update --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_publish_update_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__publish_update_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publish_update_decision --> emel__memory__coordinator__hybrid__done : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publishing_batch --> emel__memory__coordinator__hybrid__publish_batch_decision : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_publish_batch_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_109_49__
  emel__memory__coordinator__hybrid__publishing_batch --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_publish_batch_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__publish_batch_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publish_batch_decision --> emel__memory__coordinator__hybrid__done : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publishing_full --> emel__memory__coordinator__hybrid__publish_full_decision : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__valid_publish_full_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_113_48__
  emel__memory__coordinator__hybrid__publishing_full --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__invalid_publish_full_context_] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_68_46__
  emel__memory__coordinator__hybrid__publish_full_decision --> emel__memory__coordinator__hybrid__errored : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_failed_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__publish_full_decision --> emel__memory__coordinator__hybrid__done : [boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__guard__phase_ok_] / boost__sml__front__none
  emel__memory__coordinator__hybrid__done --> emel__memory__coordinator__hybrid__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_memory_coordinator_hybrid_actions_hpp_117_35__
  emel__memory__coordinator__hybrid__errored --> emel__memory__coordinator__hybrid__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__ensure_last_error_
  emel__memory__coordinator__hybrid__initialized --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__validating_update --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__validating_batch --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__validating_full --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__preparing_update --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__prepare_update_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__preparing_batch --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__prepare_batch_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__preparing_full --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__prepare_full_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__applying_update --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__apply_update_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publishing_update --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publish_update_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publishing_batch --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publish_batch_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publishing_full --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__publish_full_decision --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__done --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
  emel__memory__coordinator__hybrid__errored --> emel__memory__coordinator__hybrid__errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__memory__coordinator__hybrid__action__on_unexpected_
