stateDiagram-v2
  [*] --> emel__model__weight_loader__initialized
  emel__model__weight_loader__initialized --> emel__model__weight_loader__loading_mmap : emel__model__weight_loader__event__load_weights [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__use_mmap_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__load_mmap_
  emel__model__weight_loader__initialized --> emel__model__weight_loader__loading_streamed : emel__model__weight_loader__event__load_weights [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__use_stream_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__load_streamed_
  emel__model__weight_loader__loading_mmap --> emel__model__weight_loader__done : emel__model__weight_loader__events__weights_loaded [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__no_error_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__store_and_dispatch_done_
  emel__model__weight_loader__loading_mmap --> emel__model__weight_loader__errored : emel__model__weight_loader__events__weights_loaded [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__has_error_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__store_and_dispatch_error_
  emel__model__weight_loader__loading_streamed --> emel__model__weight_loader__done : emel__model__weight_loader__events__weights_loaded [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__no_error_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__store_and_dispatch_done_
  emel__model__weight_loader__loading_streamed --> emel__model__weight_loader__errored : emel__model__weight_loader__events__weights_loaded [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__has_error_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__store_and_dispatch_error_
  emel__model__weight_loader__initialized --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__loading_mmap --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__loading_streamed --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__done --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__errored --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
