stateDiagram-v2
  [*] --> emel::model::parser::initialized
  emel__model__parser__initialized --> emel__model__parser__parsing_architecture : emel__model__parser__event__parse_model [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__parse_architecture_
  emel__model__parser__parsing_architecture --> emel__model__parser__mapping_architecture : emel__model__parser__events__parse_architecture_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__map_architecture_
  emel__model__parser__parsing_architecture --> emel__model__parser__errored : emel__model__parser__events__parse_architecture_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_error_
  emel__model__parser__mapping_architecture --> emel__model__parser__parsing_hparams : emel__model__parser__events__map_architecture_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__parse_hparams_
  emel__model__parser__mapping_architecture --> emel__model__parser__errored : emel__model__parser__events__map_architecture_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_error_
  emel__model__parser__parsing_hparams --> emel__model__parser__parsing_vocab : emel__model__parser__events__parse_hparams_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__parse_vocab_
  emel__model__parser__parsing_hparams --> emel__model__parser__errored : emel__model__parser__events__parse_hparams_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_error_
  emel__model__parser__parsing_vocab --> emel__model__parser__mapping_tensors : emel__model__parser__events__parse_vocab_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__map_tensors_
  emel__model__parser__parsing_vocab --> emel__model__parser__errored : emel__model__parser__events__parse_vocab_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_error_
  emel__model__parser__mapping_tensors --> emel__model__parser__done : emel__model__parser__events__map_tensors_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_done_
  emel__model__parser__mapping_tensors --> emel__model__parser__errored : emel__model__parser__events__map_tensors_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__dispatch_error_
  emel__model__parser__initialized --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__parsing_architecture --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__mapping_architecture --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__parsing_hparams --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__parsing_vocab --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__mapping_tensors --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__done --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
  emel__model__parser__errored --> emel__model__parser__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__parser__action__on_unexpected_
