stateDiagram-v2
  [*] --> emel__model__loader__initialized
  emel__model__loader__initialized --> emel__model__loader__mapping_parser : emel__model__loader__event__load [boost__sml__aux__zero_wrapper_emel__model__loader__guard__can_map_parser_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__begin_load_
  emel__model__loader__initialized --> emel__model__loader__errored : emel__model__loader__event__load [boost__sml__aux__zero_wrapper_emel__model__loader__guard__cannot_map_parser_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__mapping_parser --> emel__model__loader__map_parser_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_map_parser_
  emel__model__loader__map_parser_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__map_parser_decision --> emel__model__loader__parsing : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_can_parse_] / boost__sml__front__none
  emel__model__loader__map_parser_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_cannot_parse_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__parsing --> emel__model__loader__parse_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_parse_
  emel__model__loader__parse_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__parse_decision --> emel__model__loader__loading_weights : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_should_load_weights_and_can_load_] / boost__sml__front__none
  emel__model__loader__parse_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_should_load_weights_and_cannot_load_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__parse_decision --> emel__model__loader__structure_skipped : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_skip_weights_and_skip_structure_] / boost__sml__front__none
  emel__model__loader__parse_decision --> emel__model__loader__validating_structure : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_skip_weights_and_can_validate_structure_] / boost__sml__front__none
  emel__model__loader__parse_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_skip_weights_and_cannot_validate_structure_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__loading_weights --> emel__model__loader__load_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_load_weights_
  emel__model__loader__load_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__load_decision --> emel__model__loader__mapping_layers : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_can_map_layers_] / boost__sml__front__none
  emel__model__loader__load_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_cannot_map_layers_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__mapping_layers --> emel__model__loader__map_layers_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_map_layers_
  emel__model__loader__map_layers_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__map_layers_decision --> emel__model__loader__structure_skipped : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_skip_structure_] / boost__sml__front__none
  emel__model__loader__map_layers_decision --> emel__model__loader__validating_structure : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_can_validate_structure_] / boost__sml__front__none
  emel__model__loader__map_layers_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_cannot_validate_structure_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__validating_structure --> emel__model__loader__structure_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_validate_structure_
  emel__model__loader__structure_skipped --> emel__model__loader__structure_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__skip_validate_structure_
  emel__model__loader__structure_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__structure_decision --> emel__model__loader__validating_architecture : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_has_arch_validate_and_can_validate_architecture_] / boost__sml__front__none
  emel__model__loader__structure_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_has_arch_validate_and_cannot_validate_architecture_] / boost__sml__aux__zero_wrapper_emel__model__loader__action__set_invalid_argument_
  emel__model__loader__structure_decision --> emel__model__loader__done : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_and_no_arch_validate_] / boost__sml__front__none
  emel__model__loader__validating_architecture --> emel__model__loader__architecture_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__run_validate_architecture_
  emel__model__loader__architecture_decision --> emel__model__loader__errored : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__loader__architecture_decision --> emel__model__loader__done : [boost__sml__aux__zero_wrapper_emel__model__loader__guard__phase_ok_] / boost__sml__front__none
  emel__model__loader__done --> emel__model__loader__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__publish_done_
  emel__model__loader__errored --> emel__model__loader__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__loader__action__publish_error_
  emel__model__loader__initialized --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__mapping_parser --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__map_parser_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__parsing --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__parse_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__loading_weights --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__load_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__mapping_layers --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__map_layers_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__validating_structure --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__structure_skipped --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__structure_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__validating_architecture --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__architecture_decision --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__done --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
  emel__model__loader__errored --> emel__model__loader__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_model_loader_sm_hpp_33_32__] / boost__sml__aux__zero_wrapper_emel__model__loader__action__on_unexpected_
