stateDiagram-v2
  [*] --> emel__model__weight_loader__initialized
  emel__model__weight_loader__initialized --> emel__model__weight_loader__selecting : emel__model__weight_loader__event__load_weights [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__begin_load_
  emel__model__weight_loader__selecting --> emel__model__weight_loader__strategy_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__select_strategy_
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__initializing : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_use_mmap_and_can_init_mappings_] / boost__sml__front__none
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__loading_mmap : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_use_mmap_and_skip_init_mappings_] / boost__sml__front__none
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_use_mmap_and_cannot_init_mappings_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__set_invalid_argument_
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__loading_streamed : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_use_stream_and_can_load_streamed_] / boost__sml__front__none
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_use_stream_and_cannot_load_streamed_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__set_invalid_argument_
  emel__model__weight_loader__initializing --> emel__model__weight_loader__init_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__run_init_mappings_
  emel__model__weight_loader__init_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__init_decision --> emel__model__weight_loader__loading_mmap : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_can_load_mmap_] / boost__sml__front__none
  emel__model__weight_loader__init_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_cannot_load_mmap_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__set_invalid_argument_
  emel__model__weight_loader__loading_mmap --> emel__model__weight_loader__load_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__run_load_mmap_
  emel__model__weight_loader__loading_streamed --> emel__model__weight_loader__load_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__run_load_streamed_
  emel__model__weight_loader__load_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__load_decision --> emel__model__weight_loader__validating : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_can_validate_] / boost__sml__front__none
  emel__model__weight_loader__load_decision --> emel__model__weight_loader__cleanup_decision : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_skip_validate_] / boost__sml__front__none
  emel__model__weight_loader__load_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_cannot_validate_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__set_invalid_argument_
  emel__model__weight_loader__validating --> emel__model__weight_loader__validation_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__run_validate_
  emel__model__weight_loader__validation_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__validation_decision --> emel__model__weight_loader__cleanup_decision : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_] / boost__sml__front__none
  emel__model__weight_loader__cleanup_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__cleanup_decision --> emel__model__weight_loader__cleaning_up : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_can_clean_up_] / boost__sml__front__none
  emel__model__weight_loader__cleanup_decision --> emel__model__weight_loader__done : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_skip_clean_up_] / boost__sml__front__none
  emel__model__weight_loader__cleanup_decision --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_and_cannot_clean_up_] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__set_invalid_argument_
  emel__model__weight_loader__cleaning_up --> emel__model__weight_loader__cleanup_result : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__run_clean_up_
  emel__model__weight_loader__cleanup_result --> emel__model__weight_loader__errored : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_failed_] / boost__sml__front__none
  emel__model__weight_loader__cleanup_result --> emel__model__weight_loader__done : [boost__sml__aux__zero_wrapper_emel__model__weight_loader__guard__phase_ok_] / boost__sml__front__none
  emel__model__weight_loader__done --> emel__model__weight_loader__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__publish_done_
  emel__model__weight_loader__errored --> emel__model__weight_loader__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__publish_error_
  emel__model__weight_loader__initialized --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__selecting --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__strategy_decision --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__initializing --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__init_decision --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__loading_mmap --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__loading_streamed --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__load_decision --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__validating --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__validation_decision --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__cleanup_decision --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__cleaning_up --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__cleanup_result --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__done --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
  emel__model__weight_loader__errored --> emel__model__weight_loader__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__model__weight_loader__action__on_unexpected_
