stateDiagram-v2
  [*] --> emel::sampler::token_selector::initialized
  emel__sampler__token_selector__initialized --> emel__sampler__token_selector__validating : emel__sampler__token_selector__event__select_token [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_18_44__
  emel__sampler__token_selector__validating --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_sm_hpp_43_11__
  emel__sampler__token_selector__validating --> emel__sampler__token_selector__validating : emel__sampler__token_selector__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_25_38__
  emel__sampler__token_selector__validating --> emel__sampler__token_selector__selecting_token : emel__sampler__token_selector__events__validate_done [boost__sml__aux__zero_wrapper_emel__sampler__token_selector__guard__has_candidates_] / boost__sml__front__none
  emel__sampler__token_selector__validating --> emel__sampler__token_selector__errored : emel__sampler__token_selector__events__validate_done [boost__sml__aux__zero_wrapper_emel__sampler__token_selector__guard__no_candidates_] / boost__sml__front__none
  emel__sampler__token_selector__validating --> emel__sampler__token_selector__errored : emel__sampler__token_selector__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__token_selector__selecting_token --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_sm_hpp_80_11__
  emel__sampler__token_selector__selecting_token --> emel__sampler__token_selector__selecting_token : emel__sampler__token_selector__event__select [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_45_36__
  emel__sampler__token_selector__selecting_token --> emel__sampler__token_selector__done : emel__sampler__token_selector__events__select_done [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__token_selector__selecting_token --> emel__sampler__token_selector__errored : emel__sampler__token_selector__events__select_error [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__token_selector__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_sm_hpp_113_11__
  emel__sampler__token_selector__done --> emel__sampler__token_selector__initialized : emel__sampler__token_selector__events__token_selection_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_106_49__
  emel__sampler__token_selector__done --> emel__sampler__token_selector__initialized : emel__sampler__token_selector__events__token_selection_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_110_50__
  emel__sampler__token_selector__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_sm_hpp_130_11__
  emel__sampler__token_selector__errored --> emel__sampler__token_selector__initialized : emel__sampler__token_selector__events__token_selection_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__token_selector__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_token_selector_actions_hpp_110_50__
