stateDiagram-v2
  [*] --> emel__sampler__pipeline__initialized
  emel__sampler__pipeline__initialized --> emel__sampler__pipeline__preparing_candidates : emel__sampler__pipeline__event__sample [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__begin_sample_
  emel__sampler__pipeline__preparing_candidates --> emel__sampler__pipeline__prepare_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__run_prepare_candidates_
  emel__sampler__pipeline__prepare_decision --> emel__sampler__pipeline__errored : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_failed_] / boost__sml__front__none
  emel__sampler__pipeline__prepare_decision --> emel__sampler__pipeline__sampling : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_ok_and_has_more_samplers_] / boost__sml__front__none
  emel__sampler__pipeline__prepare_decision --> emel__sampler__pipeline__selecting_token : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_ok_and_no_more_samplers_] / boost__sml__front__none
  emel__sampler__pipeline__sampling --> emel__sampler__pipeline__sampling_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__run_apply_sampling_
  emel__sampler__pipeline__sampling_decision --> emel__sampler__pipeline__errored : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_failed_] / boost__sml__front__none
  emel__sampler__pipeline__sampling_decision --> emel__sampler__pipeline__sampling : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_ok_and_has_more_samplers_] / boost__sml__front__none
  emel__sampler__pipeline__sampling_decision --> emel__sampler__pipeline__selecting_token : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_ok_and_no_more_samplers_] / boost__sml__front__none
  emel__sampler__pipeline__selecting_token --> emel__sampler__pipeline__select_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__run_select_token_
  emel__sampler__pipeline__select_decision --> emel__sampler__pipeline__errored : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_failed_] / boost__sml__front__none
  emel__sampler__pipeline__select_decision --> emel__sampler__pipeline__done : [boost__sml__aux__zero_wrapper_emel__sampler__pipeline__guard__phase_ok_] / boost__sml__front__none
  emel__sampler__pipeline__done --> emel__sampler__pipeline__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__publish_done_
  emel__sampler__pipeline__errored --> emel__sampler__pipeline__initialized : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__publish_error_
  emel__sampler__pipeline__initialized --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__preparing_candidates --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__prepare_decision --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__sampling --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__sampling_decision --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__selecting_token --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__select_decision --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__done --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
  emel__sampler__pipeline__errored --> emel__sampler__pipeline__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_pipeline_sm_hpp_25_32__] / boost__sml__aux__zero_wrapper_emel__sampler__pipeline__action__on_unexpected_
