stateDiagram-v2
  [*] --> emel::sampler::candidate_builder::initialized
  emel__sampler__candidate_builder__initialized --> emel__sampler__candidate_builder__validating : emel__sampler__candidate_builder__event__build [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_14_37__
  emel__sampler__candidate_builder__validating --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_sm_hpp_48_11__
  emel__sampler__candidate_builder__validating --> emel__sampler__candidate_builder__validating : emel__sampler__candidate_builder__event__validate [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_19_38__
  emel__sampler__candidate_builder__validating --> emel__sampler__candidate_builder__building_candidates : emel__sampler__candidate_builder__events__validate_done [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__candidate_builder__validating --> emel__sampler__candidate_builder__errored : emel__sampler__candidate_builder__events__validate_error [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__candidate_builder__building_candidates --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_sm_hpp_81_11__
  emel__sampler__candidate_builder__building_candidates --> emel__sampler__candidate_builder__building_candidates : emel__sampler__candidate_builder__event__build_candidates [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_35_46__
  emel__sampler__candidate_builder__building_candidates --> emel__sampler__candidate_builder__normalizing_scores : emel__sampler__candidate_builder__events__build_candidates_done [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__candidate_builder__building_candidates --> emel__sampler__candidate_builder__errored : emel__sampler__candidate_builder__events__build_candidates_error [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__candidate_builder__normalizing_scores --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_sm_hpp_114_11__
  emel__sampler__candidate_builder__normalizing_scores --> emel__sampler__candidate_builder__normalizing_scores : emel__sampler__candidate_builder__event__normalize_scores [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_52_46__
  emel__sampler__candidate_builder__normalizing_scores --> emel__sampler__candidate_builder__done : emel__sampler__candidate_builder__events__normalize_scores_done [boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__guard__has_candidates_] / boost__sml__front__none
  emel__sampler__candidate_builder__normalizing_scores --> emel__sampler__candidate_builder__errored : emel__sampler__candidate_builder__events__normalize_scores_done [boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__guard__no_candidates_] / boost__sml__front__none
  emel__sampler__candidate_builder__normalizing_scores --> emel__sampler__candidate_builder__errored : emel__sampler__candidate_builder__events__normalize_scores_error [boost__sml__front__always] / boost__sml__front__none
  emel__sampler__candidate_builder__done --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_sm_hpp_148_11__
  emel__sampler__candidate_builder__done --> emel__sampler__candidate_builder__initialized : emel__sampler__candidate_builder__events__build_done [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_77_39__
  emel__sampler__candidate_builder__done --> emel__sampler__candidate_builder__initialized : emel__sampler__candidate_builder__events__build_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_84_40__
  emel__sampler__candidate_builder__errored --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_sm_hpp_163_11__
  emel__sampler__candidate_builder__errored --> emel__sampler__candidate_builder__initialized : emel__sampler__candidate_builder__events__build_error [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__sampler__candidate_builder__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_sampler_candidate_builder_actions_hpp_84_40__
