stateDiagram-v2
  [*] --> emel__telemetry__exporter__initialized
  emel__telemetry__exporter__initialized --> emel__telemetry__exporter__configuring : emel__telemetry__exporter__event__configure [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_configure_
  emel__telemetry__exporter__configuring --> emel__telemetry__exporter__configure_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_validate_config_
  emel__telemetry__exporter__configure_decision --> emel__telemetry__exporter__errored : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__configure_decision --> emel__telemetry__exporter__initialized : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_done_
  emel__telemetry__exporter__initialized --> emel__telemetry__exporter__starting : emel__telemetry__exporter__event__start [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_start_
  emel__telemetry__exporter__starting --> emel__telemetry__exporter__start_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_start_
  emel__telemetry__exporter__start_decision --> emel__telemetry__exporter__errored : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__start_decision --> emel__telemetry__exporter__running : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_done_
  emel__telemetry__exporter__running --> emel__telemetry__exporter__collecting : emel__telemetry__exporter__event__tick [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_tick_
  emel__telemetry__exporter__collecting --> emel__telemetry__exporter__collect_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_collect_batch_
  emel__telemetry__exporter__collect_decision --> emel__telemetry__exporter__errored : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__collect_decision --> emel__telemetry__exporter__flushing : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_and_has_batch_] / boost__sml__front__none
  emel__telemetry__exporter__collect_decision --> emel__telemetry__exporter__running : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_and_no_batch_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_done_
  emel__telemetry__exporter__flushing --> emel__telemetry__exporter__flush_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_flush_batch_
  emel__telemetry__exporter__flush_decision --> emel__telemetry__exporter__backing_off : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__front__none
  emel__telemetry__exporter__flush_decision --> emel__telemetry__exporter__running : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_done_
  emel__telemetry__exporter__backing_off --> emel__telemetry__exporter__backoff_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_backoff_
  emel__telemetry__exporter__backoff_decision --> emel__telemetry__exporter__errored : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__backoff_decision --> emel__telemetry__exporter__running : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__running --> emel__telemetry__exporter__stopping : emel__telemetry__exporter__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_stop_
  emel__telemetry__exporter__initialized --> emel__telemetry__exporter__stopping : emel__telemetry__exporter__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_stop_
  emel__telemetry__exporter__errored --> emel__telemetry__exporter__stopping : emel__telemetry__exporter__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__begin_stop_
  emel__telemetry__exporter__stopping --> emel__telemetry__exporter__stop_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_stop_
  emel__telemetry__exporter__stop_decision --> emel__telemetry__exporter__errored : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_failed_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_error_
  emel__telemetry__exporter__stop_decision --> emel__telemetry__exporter__initialized : [boost__sml__aux__zero_wrapper_emel__telemetry__exporter__guard__phase_ok_] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__publish_done_
  emel__telemetry__exporter__initialized --> emel__telemetry__exporter__initialized : emel__telemetry__exporter__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_reset_
  emel__telemetry__exporter__errored --> emel__telemetry__exporter__initialized : emel__telemetry__exporter__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__run_reset_
  emel__telemetry__exporter__initialized --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__configuring --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__configure_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__starting --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__start_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__running --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__collecting --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__collect_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__flushing --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__flush_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__backing_off --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__backoff_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__stopping --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__stop_decision --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
  emel__telemetry__exporter__errored --> emel__telemetry__exporter__errored : boost__sml__back___ [boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_exporter_sm_hpp_31_32__] / boost__sml__aux__zero_wrapper_emel__telemetry__exporter__action__on_unexpected_
