stateDiagram-v2
  [*] --> emel__telemetry__provider__initialized
  emel__telemetry__provider__initialized --> emel__telemetry__provider__configuring : emel__telemetry__provider__event__configure [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_23_41__
  emel__telemetry__provider__configuring --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_sm_hpp_44_11__
  emel__telemetry__provider__configuring --> emel__telemetry__provider__configuring : emel__telemetry__provider__event__validate_config [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_29_45__
  emel__telemetry__provider__configuring --> emel__telemetry__provider__initialized : emel__telemetry__provider__events__configure_done [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__configuring --> emel__telemetry__provider__errored : emel__telemetry__provider__events__configure_error [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__initialized --> emel__telemetry__provider__starting : emel__telemetry__provider__event__start [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_38_37__
  emel__telemetry__provider__starting --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_sm_hpp_72_11__
  emel__telemetry__provider__starting --> emel__telemetry__provider__starting : emel__telemetry__provider__event__run_start [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_42_35__
  emel__telemetry__provider__starting --> emel__telemetry__provider__running : emel__telemetry__provider__events__start_done [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__starting --> emel__telemetry__provider__errored : emel__telemetry__provider__events__start_error [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__running --> emel__telemetry__provider__publishing : emel__telemetry__provider__event__publish [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_54_39__
  emel__telemetry__provider__publishing --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_sm_hpp_100_11__
  emel__telemetry__provider__publishing --> emel__telemetry__provider__publishing : emel__telemetry__provider__event__publish_record [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_59_44__
  emel__telemetry__provider__publishing --> emel__telemetry__provider__running : emel__telemetry__provider__events__publish_record_done [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__publishing --> emel__telemetry__provider__errored : emel__telemetry__provider__events__publish_record_error [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__running --> emel__telemetry__provider__stopping : emel__telemetry__provider__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_79_36__
  emel__telemetry__provider__initialized --> emel__telemetry__provider__stopping : emel__telemetry__provider__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_79_36__
  emel__telemetry__provider__errored --> emel__telemetry__provider__stopping : emel__telemetry__provider__event__stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_79_36__
  emel__telemetry__provider__stopping --> boost__sml__front__internal : on_entry [boost__sml__front__always] / boost__sml__aux__zero_wrapper__lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_sm_hpp_132_11__
  emel__telemetry__provider__stopping --> emel__telemetry__provider__stopping : emel__telemetry__provider__event__run_stop [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_83_34__
  emel__telemetry__provider__stopping --> emel__telemetry__provider__initialized : emel__telemetry__provider__events__stop_done [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__stopping --> emel__telemetry__provider__errored : emel__telemetry__provider__events__stop_error [boost__sml__front__always] / boost__sml__front__none
  emel__telemetry__provider__initialized --> emel__telemetry__provider__initialized : emel__telemetry__provider__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_88_35__
  emel__telemetry__provider__errored --> emel__telemetry__provider__initialized : emel__telemetry__provider__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__telemetry__provider__action___lambda_at__Users_gabrielwillen_VSCode_stateforward_emel_emel_cpp_src_emel_telemetry_provider_actions_hpp_88_35__
