stateDiagram-v2
  direction TB
  [*] --> ready_docsgen_tensor_view_policy_
  ready_docsgen_tensor_view_policy_ --> capture_tensor_view_request_decision_docsgen_tensor_view_policy_ : capture_tensor_view_runtime_docsgen_tensor_view_policy_ [always] / begin_capture_tensor_view_
  capture_tensor_view_request_decision_docsgen_tensor_view_policy_ --> capture_tensor_view_exec_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [capture_tensor_view_request_valid_] / none
  capture_tensor_view_request_decision_docsgen_tensor_view_policy_ --> errored_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [capture_tensor_view_request_invalid_] / mark_invalid_request_
  capture_tensor_view_exec_docsgen_tensor_view_policy_ --> capture_tensor_view_result_decision_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [always] / exec_capture_tensor_view_
  capture_tensor_view_result_decision_docsgen_tensor_view_policy_ --> done_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [operation_succeeded_] / none
  capture_tensor_view_result_decision_docsgen_tensor_view_policy_ --> errored_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [operation_failed_with_error_] / mark_error_from_operation_
  capture_tensor_view_result_decision_docsgen_tensor_view_policy_ --> errored_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [operation_failed_without_error_] / mark_internal_error_
  done_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [always] / publish_done_
  errored_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : completion_capture_tensor_view_runtime_docsgen_tensor_view_policy__ [always] / publish_error_
  ready_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
  capture_tensor_view_request_decision_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
  capture_tensor_view_exec_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
  capture_tensor_view_result_decision_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
  done_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
  errored_docsgen_tensor_view_policy_ --> ready_docsgen_tensor_view_policy_ : _ [always] / on_unexpected_
