stateDiagram-v2
  [*] --> emel__tensor__lifetime_analyzer__idle
  emel__tensor__lifetime_analyzer__idle --> emel__tensor__lifetime_analyzer__validating : emel__tensor__lifetime_analyzer__event__analyze [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_analyze_
  emel__tensor__lifetime_analyzer__validating --> emel__tensor__lifetime_analyzer__validate_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_validate_
  emel__tensor__lifetime_analyzer__validate_decision --> emel__tensor__lifetime_analyzer__errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__validate_decision --> emel__tensor__lifetime_analyzer__collecting_ranges : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__collecting_ranges --> emel__tensor__lifetime_analyzer__collect_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_collect_ranges_
  emel__tensor__lifetime_analyzer__collect_decision --> emel__tensor__lifetime_analyzer__errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__collect_decision --> emel__tensor__lifetime_analyzer__publishing : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__publishing --> emel__tensor__lifetime_analyzer__publish_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_publish_
  emel__tensor__lifetime_analyzer__publish_decision --> emel__tensor__lifetime_analyzer__errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__publish_decision --> emel__tensor__lifetime_analyzer__done : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__done --> emel__tensor__lifetime_analyzer__idle : [boost__sml__front__always] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__errored --> emel__tensor__lifetime_analyzer__idle : [boost__sml__front__always] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__idle --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__validating --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__validate_decision --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__collecting_ranges --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__collect_decision --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__publishing --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__publish_decision --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__done --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__errored --> emel__tensor__lifetime_analyzer__reset_decision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__reset_decision --> emel__tensor__lifetime_analyzer__errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__reset_decision --> emel__tensor__lifetime_analyzer__idle : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__idle --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__validating --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__validate_decision --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__collecting_ranges --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__collect_decision --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__publishing --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__publish_decision --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__done --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__errored --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__reset_decision --> emel__tensor__lifetime_analyzer__errored : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
