stateDiagram-v2
  [*] --> emel__tensor__lifetime_analyzer__Idle
  emel__tensor__lifetime_analyzer__Idle --> emel__tensor__lifetime_analyzer__Validating : emel__tensor__lifetime_analyzer__event__analyze [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_analyze_
  emel__tensor__lifetime_analyzer__Validating --> emel__tensor__lifetime_analyzer__ValidateDecision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_validate_
  emel__tensor__lifetime_analyzer__ValidateDecision --> emel__tensor__lifetime_analyzer__Errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__ValidateDecision --> emel__tensor__lifetime_analyzer__CollectingRanges : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__CollectingRanges --> emel__tensor__lifetime_analyzer__CollectDecision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_collect_ranges_
  emel__tensor__lifetime_analyzer__CollectDecision --> emel__tensor__lifetime_analyzer__Errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__CollectDecision --> emel__tensor__lifetime_analyzer__Publishing : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__Publishing --> emel__tensor__lifetime_analyzer__PublishDecision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__run_publish_
  emel__tensor__lifetime_analyzer__PublishDecision --> emel__tensor__lifetime_analyzer__Errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__PublishDecision --> emel__tensor__lifetime_analyzer__Done : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__Done --> emel__tensor__lifetime_analyzer__Idle : [boost__sml__front__always] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__Errored --> emel__tensor__lifetime_analyzer__Idle : [boost__sml__front__always] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__Idle --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__Validating --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__ValidateDecision --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__CollectingRanges --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__CollectDecision --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__Publishing --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__PublishDecision --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__Done --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__Errored --> emel__tensor__lifetime_analyzer__ResetDecision : emel__tensor__lifetime_analyzer__event__reset [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__begin_reset_
  emel__tensor__lifetime_analyzer__ResetDecision --> emel__tensor__lifetime_analyzer__Errored : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_failed_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__ResetDecision --> emel__tensor__lifetime_analyzer__Idle : [boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__guard__phase_ok_] / boost__sml__front__none
  emel__tensor__lifetime_analyzer__Idle --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__Validating --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__ValidateDecision --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__CollectingRanges --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__CollectDecision --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__Publishing --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__PublishDecision --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__Done --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__Errored --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
  emel__tensor__lifetime_analyzer__ResetDecision --> emel__tensor__lifetime_analyzer__Errored : internal_event [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tensor__lifetime_analyzer__action__on_unexpected_
