stateDiagram-v2
  direction TB
  [*] --> emel__tokenizer__initialized
  emel__tokenizer__initialized --> emel__tokenizer__building_special_tokens : emel__tokenizer__event__tokenize [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__can_tokenize_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__begin_tokenize_
  emel__tokenizer__initialized --> emel__tokenizer__errored : emel__tokenizer__event__tokenize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__reject_invalid_
  emel__tokenizer__done --> emel__tokenizer__building_special_tokens : emel__tokenizer__event__tokenize [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__can_tokenize_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__begin_tokenize_
  emel__tokenizer__done --> emel__tokenizer__errored : emel__tokenizer__event__tokenize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__reject_invalid_
  emel__tokenizer__errored --> emel__tokenizer__building_special_tokens : emel__tokenizer__event__tokenize [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__can_tokenize_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__begin_tokenize_
  emel__tokenizer__errored --> emel__tokenizer__errored : emel__tokenizer__event__tokenize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__reject_invalid_
  emel__tokenizer__unexpected --> emel__tokenizer__building_special_tokens : emel__tokenizer__event__tokenize [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__can_tokenize_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__begin_tokenize_
  emel__tokenizer__unexpected --> emel__tokenizer__unexpected : emel__tokenizer__event__tokenize [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__reject_invalid_
  emel__tokenizer__building_special_tokens --> emel__tokenizer__special_tokens_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__build_special_tokens_
  emel__tokenizer__special_tokens_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_failed_] / boost__sml__front__none
  emel__tokenizer__special_tokens_decision --> emel__tokenizer__partitioning_with_specials : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__has_special_tokens_] / boost__sml__front__none
  emel__tokenizer__special_tokens_decision --> emel__tokenizer__partitioning_raw : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__no_special_tokens_] / boost__sml__front__none
  emel__tokenizer__partitioning_raw --> emel__tokenizer__partitioning_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__partition_raw_
  emel__tokenizer__partitioning_with_specials --> emel__tokenizer__partitioning_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__partition_with_specials_
  emel__tokenizer__partitioning_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_failed_] / boost__sml__front__none
  emel__tokenizer__partitioning_decision --> emel__tokenizer__selecting_backend : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_ok_] / boost__sml__front__none
  emel__tokenizer__selecting_backend --> emel__tokenizer__selecting_backend_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__select_backend_
  emel__tokenizer__selecting_backend_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_failed_] / boost__sml__front__none
  emel__tokenizer__selecting_backend_decision --> emel__tokenizer__prefix_decision : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_ok_] / boost__sml__front__none
  emel__tokenizer__prefix_decision --> emel__tokenizer__encoding_ready : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__bos_ready_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__append_bos_
  emel__tokenizer__prefix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__bos_no_capacity_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_capacity_error_
  emel__tokenizer__prefix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__bos_invalid_id_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_invalid_id_error_
  emel__tokenizer__prefix_decision --> emel__tokenizer__encoding_ready : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__no_prefix_] / boost__sml__front__none
  emel__tokenizer__encoding_ready --> emel__tokenizer__suffix_decision : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__no_more_fragments_] / boost__sml__front__none
  emel__tokenizer__encoding_ready --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__more_fragments_no_capacity_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_capacity_error_
  emel__tokenizer__encoding_ready --> emel__tokenizer__encoding_token_fragment : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__more_fragments_token_] / boost__sml__front__none
  emel__tokenizer__encoding_ready --> emel__tokenizer__encoding_raw_fragment : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__more_fragments_raw_] / boost__sml__front__none
  emel__tokenizer__encoding_token_fragment --> emel__tokenizer__encoding_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__append_fragment_token_
  emel__tokenizer__encoding_raw_fragment --> emel__tokenizer__encoding_decision : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__encode_raw_fragment_
  emel__tokenizer__encoding_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_failed_] / boost__sml__front__none
  emel__tokenizer__encoding_decision --> emel__tokenizer__encoding_ready : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__phase_ok_] / boost__sml__front__none
  emel__tokenizer__suffix_decision --> emel__tokenizer__finalizing : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__sep_ready_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__append_sep_
  emel__tokenizer__suffix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__sep_no_capacity_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_capacity_error_
  emel__tokenizer__suffix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__sep_invalid_id_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_invalid_id_error_
  emel__tokenizer__suffix_decision --> emel__tokenizer__finalizing : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__eos_ready_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__append_eos_
  emel__tokenizer__suffix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__eos_no_capacity_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_capacity_error_
  emel__tokenizer__suffix_decision --> emel__tokenizer__errored : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__eos_invalid_id_] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__set_invalid_id_error_
  emel__tokenizer__suffix_decision --> emel__tokenizer__finalizing : [boost__sml__aux__zero_wrapper_emel__tokenizer__guard__no_suffix_] / boost__sml__front__none
  emel__tokenizer__finalizing --> emel__tokenizer__done : [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__finalize_
  emel__tokenizer__initialized --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__building_special_tokens --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__special_tokens_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__partitioning_raw --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__partitioning_with_specials --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__partitioning_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__selecting_backend --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__selecting_backend_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__prefix_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__encoding_ready --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__encoding_token_fragment --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__encoding_raw_fragment --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__encoding_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__suffix_decision --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__finalizing --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__done --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__errored --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
  emel__tokenizer__unexpected --> emel__tokenizer__unexpected : boost__sml__back___ [boost__sml__front__always] / boost__sml__aux__zero_wrapper_emel__tokenizer__action__on_unexpected_
