@startuml

[*] --> emel::batch::splitter::initialized
emel::batch::splitter::initialized --> emel::batch::splitter::validating : emel::batch::splitter::event::split
emel::batch::splitter::validating --> boost::sml::front::internal : on_entry
emel::batch::splitter::validating --> emel::batch::splitter::validating : emel::batch::splitter::event::validate
emel::batch::splitter::validating --> emel::batch::splitter::normalizing_batch : emel::batch::splitter::events::validate_done
emel::batch::splitter::validating --> emel::batch::splitter::errored : emel::batch::splitter::events::validate_error
emel::batch::splitter::normalizing_batch --> boost::sml::front::internal : on_entry
emel::batch::splitter::normalizing_batch --> emel::batch::splitter::normalizing_batch : emel::batch::splitter::event::normalize_batch
emel::batch::splitter::normalizing_batch --> emel::batch::splitter::splitting : emel::batch::splitter::events::normalize_done
emel::batch::splitter::normalizing_batch --> emel::batch::splitter::errored : emel::batch::splitter::events::normalize_error
emel::batch::splitter::splitting --> boost::sml::front::internal : on_entry
emel::batch::splitter::splitting --> emel::batch::splitter::splitting : emel::batch::splitter::event::create_ubatches
emel::batch::splitter::splitting --> emel::batch::splitter::publishing : emel::batch::splitter::events::split_done
emel::batch::splitter::splitting --> emel::batch::splitter::errored : emel::batch::splitter::events::split_error
emel::batch::splitter::publishing --> boost::sml::front::internal : on_entry
emel::batch::splitter::publishing --> emel::batch::splitter::publishing : emel::batch::splitter::event::publish
emel::batch::splitter::publishing --> emel::batch::splitter::done : emel::batch::splitter::events::publish_done
emel::batch::splitter::publishing --> emel::batch::splitter::errored : emel::batch::splitter::events::publish_error
emel::batch::splitter::done --> boost::sml::front::internal : on_entry
emel::batch::splitter::done --> emel::batch::splitter::initialized : emel::batch::splitter::events::splitting_done
emel::batch::splitter::done --> emel::batch::splitter::initialized : emel::batch::splitter::events::splitting_error
emel::batch::splitter::errored --> boost::sml::front::internal : on_entry
emel::batch::splitter::errored --> emel::batch::splitter::initialized : emel::batch::splitter::events::splitting_error

@enduml
