@startuml

[*] --> uninitialized
uninitialized --> initializing : emel::buffer::allocator::event::initialize\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::valid_initialize>]
initializing --> ready : emel::buffer::allocator::events::initialize_done
initializing --> failed : emel::buffer::allocator::events::initialize_error
ready --> reserving_n_size : emel::buffer::allocator::event::reserve_n_size\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve_n_size>]
allocated --> reserving_n_size : emel::buffer::allocator::event::reserve_n_size\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve_n_size>]
reserving_n_size --> ready : emel::buffer::allocator::events::reserve_n_size_done
reserving_n_size --> failed : emel::buffer::allocator::events::reserve_n_size_error
ready --> reserving : emel::buffer::allocator::event::reserve_n\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve_n>]
allocated --> reserving : emel::buffer::allocator::event::reserve_n\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve_n>]
ready --> reserving : emel::buffer::allocator::event::reserve\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve>]
allocated --> reserving : emel::buffer::allocator::event::reserve\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_reserve>]
reserving --> ready : emel::buffer::allocator::events::reserve_done
reserving --> failed : emel::buffer::allocator::events::reserve_error
ready --> allocating_graph : emel::buffer::allocator::event::alloc_graph\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_alloc_graph>]
allocated --> allocating_graph : emel::buffer::allocator::event::alloc_graph\n [boost::sml::aux::zero_wrapper<emel::buffer::allocator::guard::can_alloc_graph>]
allocating_graph --> allocated : emel::buffer::allocator::events::alloc_graph_done
allocating_graph --> failed : emel::buffer::allocator::events::alloc_graph_error
uninitialized --> releasing : emel::buffer::allocator::event::release
initializing --> releasing : emel::buffer::allocator::event::release
ready --> releasing : emel::buffer::allocator::event::release
reserving_n_size --> releasing : emel::buffer::allocator::event::release
reserving --> releasing : emel::buffer::allocator::event::release
allocating_graph --> releasing : emel::buffer::allocator::event::release
allocated --> releasing : emel::buffer::allocator::event::release
failed --> releasing : emel::buffer::allocator::event::release
releasing --> uninitialized : emel::buffer::allocator::events::release_done
releasing --> failed : emel::buffer::allocator::events::release_error

@enduml
