@startuml

[*] --> uninitialized
uninitialized --> initializing : emel::buffer::allocator::event::initialize
initializing --> boost::sml::front::internal : on_entry
initializing --> ready : emel::buffer::allocator::events::initialize_done
initializing --> failed : emel::buffer::allocator::events::initialize_error
ready --> reserving_n_size : emel::buffer::allocator::event::reserve_n_size
allocated --> reserving_n_size : emel::buffer::allocator::event::reserve_n_size
reserving_n_size --> boost::sml::front::internal : on_entry
reserving_n_size --> ready : emel::buffer::allocator::events::reserve_n_size_done
reserving_n_size --> failed : emel::buffer::allocator::events::reserve_n_size_error
ready --> reserving : emel::buffer::allocator::event::reserve_n
allocated --> reserving : emel::buffer::allocator::event::reserve_n
ready --> reserving : emel::buffer::allocator::event::reserve
allocated --> reserving : emel::buffer::allocator::event::reserve
reserving --> boost::sml::front::internal : on_entry
reserving --> boost::sml::front::internal : on_entry
reserving --> ready : emel::buffer::allocator::events::reserve_done
reserving --> failed : emel::buffer::allocator::events::reserve_error
ready --> allocating_graph : emel::buffer::allocator::event::alloc_graph
allocated --> allocating_graph : emel::buffer::allocator::event::alloc_graph
allocating_graph --> boost::sml::front::internal : on_entry
allocating_graph --> allocated : emel::buffer::allocator::events::alloc_graph_done
allocating_graph --> failed : emel::buffer::allocator::events::alloc_graph_error
uninitialized --> releasing : emel::buffer::allocator::event::release
initializing --> releasing : emel::buffer::allocator::event::release
ready --> releasing : emel::buffer::allocator::event::release
reserving_n_size --> releasing : emel::buffer::allocator::event::release
reserving --> releasing : emel::buffer::allocator::event::release
allocating_graph --> releasing : emel::buffer::allocator::event::release
allocated --> releasing : emel::buffer::allocator::event::release
failed --> releasing : emel::buffer::allocator::event::release
releasing --> boost::sml::front::internal : on_entry
releasing --> uninitialized : emel::buffer::allocator::events::release_done
releasing --> failed : emel::buffer::allocator::events::release_error
uninitialized --> failed : boost::sml::back::_
initializing --> failed : boost::sml::back::_
ready --> failed : boost::sml::back::_
reserving_n_size --> failed : boost::sml::back::_
reserving --> failed : boost::sml::back::_
allocating_graph --> failed : boost::sml::back::_
allocated --> failed : boost::sml::back::_
releasing --> failed : boost::sml::back::_
failed --> failed : boost::sml::back::_

@enduml
