@startuml

[*] --> initialized
initialized --> detokenizing : emel::codec::decoder::event::decode
detokenizing --> done : emel::codec::decoder::event::detokenized_done
detokenizing --> errored : emel::codec::decoder::event::detokenized_error

@enduml
