@startuml

[*] --> initialized
initialized --> detokenizing : emel::decoder::event::decode
detokenizing --> done : emel::decoder::event::detokenized_done
detokenizing --> errored : emel::decoder::event::detokenized_error

@enduml
