@startuml

[*] --> initialized
initialized --> tokenizing_prompt : emel::generator::event::generate
tokenizing_prompt --> prefilling : emel::generator::event::prompt_tokenized_done
tokenizing_prompt --> errored : emel::generator::event::prompt_tokenized_error
prefilling --> decoding : emel::generator::event::prefill_done
prefilling --> errored : emel::generator::event::prefill_error
decoding --> decoding : emel::generator::event::decode_step_done\n [boost::sml::aux::zero_wrapper<emel::generator::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/generator/guards.hpp:8:48)>]
decoding --> done : emel::generator::event::stop_condition_met
decoding --> errored : emel::generator::event::decode_step_error

@enduml
