@startuml

[*] --> emel::model::parser::initialized
emel::model::parser::initialized --> emel::model::parser::parsing_architecture : emel::model::parser::event::parse_model
emel::model::parser::parsing_architecture --> emel::model::parser::mapping_architecture : emel::model::parser::events::parse_architecture_done
emel::model::parser::parsing_architecture --> emel::model::parser::errored : emel::model::parser::events::parse_architecture_error
emel::model::parser::mapping_architecture --> emel::model::parser::parsing_hparams : emel::model::parser::events::map_architecture_done
emel::model::parser::mapping_architecture --> emel::model::parser::errored : emel::model::parser::events::map_architecture_error
emel::model::parser::parsing_hparams --> emel::model::parser::parsing_vocab : emel::model::parser::events::parse_hparams_done
emel::model::parser::parsing_hparams --> emel::model::parser::errored : emel::model::parser::events::parse_hparams_error
emel::model::parser::parsing_vocab --> emel::model::parser::mapping_tensors : emel::model::parser::events::parse_vocab_done
emel::model::parser::parsing_vocab --> emel::model::parser::errored : emel::model::parser::events::parse_vocab_error
emel::model::parser::mapping_tensors --> emel::model::parser::done : emel::model::parser::events::map_tensors_done
emel::model::parser::mapping_tensors --> emel::model::parser::errored : emel::model::parser::events::map_tensors_error
emel::model::parser::initialized --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::parsing_architecture --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::mapping_architecture --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::parsing_hparams --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::parsing_vocab --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::mapping_tensors --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::done --> emel::model::parser::errored : boost::sml::back::_
emel::model::parser::errored --> emel::model::parser::errored : boost::sml::back::_

@enduml
