@startuml

[*] --> initialized
initialized --> mapping_parser : emel::model::loader::event::load
mapping_parser --> parsing : emel::model::loader::event::mapping_parser_done
mapping_parser --> errored : emel::model::loader::event::unsupported_format_error
parsing --> loading_weights : emel::model::parser::events::parsing_done
parsing --> errored : emel::model::parser::events::parsing_error
loading_weights --> mapping_layers : emel::model::weight_loader::events::loading_done
loading_weights --> errored : emel::model::weight_loader::events::loading_error
mapping_layers --> validating_structure : emel::model::loader::event::layers_mapped\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:5:34)>]
mapping_layers --> errored : emel::model::loader::event::layers_mapped\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:7:35)>]
validating_structure --> validating_architecture : emel::model::loader::event::structure_validated\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:9:56)>]
validating_structure --> done : emel::model::loader::event::structure_validated\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:12:55)>]
validating_structure --> errored : emel::model::loader::event::structure_validated\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:7:35)>]
validating_architecture --> done : emel::model::loader::event::architecture_validated\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:5:34)>]
validating_architecture --> errored : emel::model::loader::event::architecture_validated\n [boost::sml::aux::zero_wrapper<emel::model::loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/loader/guards.hpp:7:35)>]

@enduml
