@startuml

[*] --> emel::model::weight_loader::initialized
emel::model::weight_loader::initialized --> emel::model::weight_loader::loading_mmap : emel::model::weight_loader::event::load_weights\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::use_mmap>]
emel::model::weight_loader::initialized --> emel::model::weight_loader::loading_streamed : emel::model::weight_loader::event::load_weights\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::use_stream>]
emel::model::weight_loader::loading_mmap --> emel::model::weight_loader::done : emel::model::weight_loader::events::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::no_error>]
emel::model::weight_loader::loading_mmap --> emel::model::weight_loader::errored : emel::model::weight_loader::events::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::has_error>]
emel::model::weight_loader::loading_streamed --> emel::model::weight_loader::done : emel::model::weight_loader::events::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::no_error>]
emel::model::weight_loader::loading_streamed --> emel::model::weight_loader::errored : emel::model::weight_loader::events::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::has_error>]
emel::model::weight_loader::initialized --> emel::model::weight_loader::errored : boost::sml::back::_
emel::model::weight_loader::loading_mmap --> emel::model::weight_loader::errored : boost::sml::back::_
emel::model::weight_loader::loading_streamed --> emel::model::weight_loader::errored : boost::sml::back::_
emel::model::weight_loader::done --> emel::model::weight_loader::errored : boost::sml::back::_
emel::model::weight_loader::errored --> emel::model::weight_loader::errored : boost::sml::back::_

@enduml
