@startuml

[*] --> emel::sampler::candidate_builder::initialized
emel::sampler::candidate_builder::initialized --> emel::sampler::candidate_builder::validating : emel::sampler::candidate_builder::event::build
emel::sampler::candidate_builder::validating --> boost::sml::front::internal : on_entry
emel::sampler::candidate_builder::validating --> emel::sampler::candidate_builder::validating : emel::sampler::candidate_builder::event::validate
emel::sampler::candidate_builder::validating --> emel::sampler::candidate_builder::building_candidates : emel::sampler::candidate_builder::events::validate_done
emel::sampler::candidate_builder::validating --> emel::sampler::candidate_builder::errored : emel::sampler::candidate_builder::events::validate_error
emel::sampler::candidate_builder::building_candidates --> boost::sml::front::internal : on_entry
emel::sampler::candidate_builder::building_candidates --> emel::sampler::candidate_builder::building_candidates : emel::sampler::candidate_builder::event::build_candidates
emel::sampler::candidate_builder::building_candidates --> emel::sampler::candidate_builder::normalizing_scores : emel::sampler::candidate_builder::events::build_candidates_done
emel::sampler::candidate_builder::building_candidates --> emel::sampler::candidate_builder::errored : emel::sampler::candidate_builder::events::build_candidates_error
emel::sampler::candidate_builder::normalizing_scores --> boost::sml::front::internal : on_entry
emel::sampler::candidate_builder::normalizing_scores --> emel::sampler::candidate_builder::normalizing_scores : emel::sampler::candidate_builder::event::normalize_scores
emel::sampler::candidate_builder::normalizing_scores --> emel::sampler::candidate_builder::done : emel::sampler::candidate_builder::events::normalize_scores_done\n [boost::sml::aux::zero_wrapper<emel::sampler::candidate_builder::guard::has_candidates>]
emel::sampler::candidate_builder::normalizing_scores --> emel::sampler::candidate_builder::errored : emel::sampler::candidate_builder::events::normalize_scores_done\n [boost::sml::aux::zero_wrapper<emel::sampler::candidate_builder::guard::no_candidates>]
emel::sampler::candidate_builder::normalizing_scores --> emel::sampler::candidate_builder::errored : emel::sampler::candidate_builder::events::normalize_scores_error
emel::sampler::candidate_builder::done --> boost::sml::front::internal : on_entry
emel::sampler::candidate_builder::done --> emel::sampler::candidate_builder::initialized : emel::sampler::candidate_builder::events::build_done
emel::sampler::candidate_builder::done --> emel::sampler::candidate_builder::initialized : emel::sampler::candidate_builder::events::build_error
emel::sampler::candidate_builder::errored --> boost::sml::front::internal : on_entry
emel::sampler::candidate_builder::errored --> emel::sampler::candidate_builder::initialized : emel::sampler::candidate_builder::events::build_error

@enduml
