@startuml

[*] --> initialized
initialized --> partitioning_special : emel::tokenizer::event::tokenize\n [boost::sml::aux::zero_wrapper<emel::tokenizer::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/tokenizer/guards.hpp:5:31)>]
partitioning_special --> selecting_backend : emel::tokenizer::event::partitioning_special_done
partitioning_special --> errored : emel::tokenizer::event::partitioning_special_error
selecting_backend --> applying_special_prefix : emel::tokenizer::event::selecting_backend_done
selecting_backend --> errored : emel::tokenizer::event::selecting_backend_error
applying_special_prefix --> encoding_fragments : emel::tokenizer::event::applying_special_prefix_done
applying_special_prefix --> errored : emel::tokenizer::event::applying_special_prefix_error
encoding_fragments --> encoding_fragments : emel::encoder::event::tokenized_done
encoding_fragments --> errored : emel::encoder::event::tokenized_error
encoding_fragments --> encoding_fragments : emel::tokenizer::event::encoding_fragment_done\n [boost::sml::aux::zero_wrapper<emel::tokenizer::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/tokenizer/guards.hpp:6:37)>]
encoding_fragments --> applying_special_suffix : emel::tokenizer::event::encoding_fragment_done\n [boost::sml::aux::zero_wrapper<emel::tokenizer::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/tokenizer/guards.hpp:7:36)>]
encoding_fragments --> errored : emel::tokenizer::event::encoding_fragment_error
applying_special_suffix --> finalizing : emel::tokenizer::event::applying_special_suffix_done
applying_special_suffix --> errored : emel::tokenizer::event::applying_special_suffix_error
finalizing --> done : emel::tokenizer::event::finalizing_done
finalizing --> errored : emel::tokenizer::event::finalizing_error

@enduml
