@startuml

[*] --> initialized
initialized --> loading_mmap : emel::model::weight_loader::event::load_weights\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:7:34)>]
initialized --> loading_streamed : emel::model::weight_loader::event::load_weights\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:10:38)>]
loading_mmap --> done : emel::model::weight_loader::event::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:13:34)>]
loading_mmap --> errored : emel::model::weight_loader::event::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:15:35)>]
loading_streamed --> done : emel::model::weight_loader::event::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:13:34)>]
loading_streamed --> errored : emel::model::weight_loader::event::weights_loaded\n [boost::sml::aux::zero_wrapper<emel::model::weight_loader::guard::(lambda at /Users/gabrielwillen/VSCode/stateforward/emel/emel.cpp/src/emel/model/weight_loader/guards.hpp:15:35)>]

@enduml
